// flow-typed signature: 8085fa62deda1584c8dc666ab05b7271
// flow-typed version: <<STUB>>/beautiful-react-hooks_v^0.20.1/flow_v0.118.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'beautiful-react-hooks'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'beautiful-react-hooks' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'beautiful-react-hooks/dist' {
  declare module.exports: any;
}

declare module 'beautiful-react-hooks/dist/useConditionalTimeout' {
  declare module.exports: any;
}

declare module 'beautiful-react-hooks/dist/useDebouncedFn' {
  declare module.exports: any;
}

declare module 'beautiful-react-hooks/dist/useDidMount' {
  declare module.exports: any;
}

declare module 'beautiful-react-hooks/dist/useDrag' {
  declare module.exports: any;
}

declare module 'beautiful-react-hooks/dist/useDragEvents' {
  declare module.exports: any;
}

declare module 'beautiful-react-hooks/dist/useGeolocation' {
  declare module.exports: any;
}

declare module 'beautiful-react-hooks/dist/useGeolocationEvents' {
  declare module.exports: any;
}

declare module 'beautiful-react-hooks/dist/useGeolocationState' {
  declare module.exports: any;
}

declare module 'beautiful-react-hooks/dist/useGlobalEvent' {
  declare module.exports: any;
}

declare module 'beautiful-react-hooks/dist/useInterval' {
  declare module.exports: any;
}

declare module 'beautiful-react-hooks/dist/useLifecycle' {
  declare module.exports: any;
}

declare module 'beautiful-react-hooks/dist/useMediaQuery' {
  declare module.exports: any;
}

declare module 'beautiful-react-hooks/dist/useMouse' {
  declare module.exports: any;
}

declare module 'beautiful-react-hooks/dist/useMouseEvents' {
  declare module.exports: any;
}

declare module 'beautiful-react-hooks/dist/useMouseState' {
  declare module.exports: any;
}

declare module 'beautiful-react-hooks/dist/useOnlineState' {
  declare module.exports: any;
}

declare module 'beautiful-react-hooks/dist/usePreviousValue' {
  declare module.exports: any;
}

declare module 'beautiful-react-hooks/dist/useThrottledFn' {
  declare module.exports: any;
}

declare module 'beautiful-react-hooks/dist/useTimeout' {
  declare module.exports: any;
}

declare module 'beautiful-react-hooks/dist/useValidatedState' {
  declare module.exports: any;
}

declare module 'beautiful-react-hooks/dist/useValueHistory' {
  declare module.exports: any;
}

declare module 'beautiful-react-hooks/dist/useViewportSpy' {
  declare module.exports: any;
}

declare module 'beautiful-react-hooks/dist/useWillUnmount' {
  declare module.exports: any;
}

declare module 'beautiful-react-hooks/dist/useWindowResize' {
  declare module.exports: any;
}

declare module 'beautiful-react-hooks/dist/useWindowScroll' {
  declare module.exports: any;
}

declare module 'beautiful-react-hooks/dist/utils/createCbSetterErrorProxy' {
  declare module.exports: any;
}

declare module 'beautiful-react-hooks/dist/utils/createHandlerSetter' {
  declare module.exports: any;
}

declare module 'beautiful-react-hooks/dist/utils/geolocationStandardOptions' {
  declare module.exports: any;
}

declare module 'beautiful-react-hooks/dist/utils/hasOwnProperty' {
  declare module.exports: any;
}

declare module 'beautiful-react-hooks/dist/utils/isSamePosition' {
  declare module.exports: any;
}

declare module 'beautiful-react-hooks/dist/utils/makePositionObject' {
  declare module.exports: any;
}

// Filename aliases
declare module 'beautiful-react-hooks/dist/index' {
  declare module.exports: $Exports<'beautiful-react-hooks/dist'>;
}
declare module 'beautiful-react-hooks/dist/index.js' {
  declare module.exports: $Exports<'beautiful-react-hooks/dist'>;
}
declare module 'beautiful-react-hooks/dist/useConditionalTimeout.js' {
  declare module.exports: $Exports<'beautiful-react-hooks/dist/useConditionalTimeout'>;
}
declare module 'beautiful-react-hooks/dist/useDebouncedFn.js' {
  declare module.exports: $Exports<'beautiful-react-hooks/dist/useDebouncedFn'>;
}
declare module 'beautiful-react-hooks/dist/useDidMount.js' {
  declare module.exports: $Exports<'beautiful-react-hooks/dist/useDidMount'>;
}
declare module 'beautiful-react-hooks/dist/useDrag.js' {
  declare module.exports: $Exports<'beautiful-react-hooks/dist/useDrag'>;
}
declare module 'beautiful-react-hooks/dist/useDragEvents.js' {
  declare module.exports: $Exports<'beautiful-react-hooks/dist/useDragEvents'>;
}
declare module 'beautiful-react-hooks/dist/useGeolocation.js' {
  declare module.exports: $Exports<'beautiful-react-hooks/dist/useGeolocation'>;
}
declare module 'beautiful-react-hooks/dist/useGeolocationEvents.js' {
  declare module.exports: $Exports<'beautiful-react-hooks/dist/useGeolocationEvents'>;
}
declare module 'beautiful-react-hooks/dist/useGeolocationState.js' {
  declare module.exports: $Exports<'beautiful-react-hooks/dist/useGeolocationState'>;
}
declare module 'beautiful-react-hooks/dist/useGlobalEvent.js' {
  declare module.exports: $Exports<'beautiful-react-hooks/dist/useGlobalEvent'>;
}
declare module 'beautiful-react-hooks/dist/useInterval.js' {
  declare module.exports: $Exports<'beautiful-react-hooks/dist/useInterval'>;
}
declare module 'beautiful-react-hooks/dist/useLifecycle.js' {
  declare module.exports: $Exports<'beautiful-react-hooks/dist/useLifecycle'>;
}
declare module 'beautiful-react-hooks/dist/useMediaQuery.js' {
  declare module.exports: $Exports<'beautiful-react-hooks/dist/useMediaQuery'>;
}
declare module 'beautiful-react-hooks/dist/useMouse.js' {
  declare module.exports: $Exports<'beautiful-react-hooks/dist/useMouse'>;
}
declare module 'beautiful-react-hooks/dist/useMouseEvents.js' {
  declare module.exports: $Exports<'beautiful-react-hooks/dist/useMouseEvents'>;
}
declare module 'beautiful-react-hooks/dist/useMouseState.js' {
  declare module.exports: $Exports<'beautiful-react-hooks/dist/useMouseState'>;
}
declare module 'beautiful-react-hooks/dist/useOnlineState.js' {
  declare module.exports: $Exports<'beautiful-react-hooks/dist/useOnlineState'>;
}
declare module 'beautiful-react-hooks/dist/usePreviousValue.js' {
  declare module.exports: $Exports<'beautiful-react-hooks/dist/usePreviousValue'>;
}
declare module 'beautiful-react-hooks/dist/useThrottledFn.js' {
  declare module.exports: $Exports<'beautiful-react-hooks/dist/useThrottledFn'>;
}
declare module 'beautiful-react-hooks/dist/useTimeout.js' {
  declare module.exports: $Exports<'beautiful-react-hooks/dist/useTimeout'>;
}
declare module 'beautiful-react-hooks/dist/useValidatedState.js' {
  declare module.exports: $Exports<'beautiful-react-hooks/dist/useValidatedState'>;
}
declare module 'beautiful-react-hooks/dist/useValueHistory.js' {
  declare module.exports: $Exports<'beautiful-react-hooks/dist/useValueHistory'>;
}
declare module 'beautiful-react-hooks/dist/useViewportSpy.js' {
  declare module.exports: $Exports<'beautiful-react-hooks/dist/useViewportSpy'>;
}
declare module 'beautiful-react-hooks/dist/useWillUnmount.js' {
  declare module.exports: $Exports<'beautiful-react-hooks/dist/useWillUnmount'>;
}
declare module 'beautiful-react-hooks/dist/useWindowResize.js' {
  declare module.exports: $Exports<'beautiful-react-hooks/dist/useWindowResize'>;
}
declare module 'beautiful-react-hooks/dist/useWindowScroll.js' {
  declare module.exports: $Exports<'beautiful-react-hooks/dist/useWindowScroll'>;
}
declare module 'beautiful-react-hooks/dist/utils/createCbSetterErrorProxy.js' {
  declare module.exports: $Exports<'beautiful-react-hooks/dist/utils/createCbSetterErrorProxy'>;
}
declare module 'beautiful-react-hooks/dist/utils/createHandlerSetter.js' {
  declare module.exports: $Exports<'beautiful-react-hooks/dist/utils/createHandlerSetter'>;
}
declare module 'beautiful-react-hooks/dist/utils/geolocationStandardOptions.js' {
  declare module.exports: $Exports<'beautiful-react-hooks/dist/utils/geolocationStandardOptions'>;
}
declare module 'beautiful-react-hooks/dist/utils/hasOwnProperty.js' {
  declare module.exports: $Exports<'beautiful-react-hooks/dist/utils/hasOwnProperty'>;
}
declare module 'beautiful-react-hooks/dist/utils/isSamePosition.js' {
  declare module.exports: $Exports<'beautiful-react-hooks/dist/utils/isSamePosition'>;
}
declare module 'beautiful-react-hooks/dist/utils/makePositionObject.js' {
  declare module.exports: $Exports<'beautiful-react-hooks/dist/utils/makePositionObject'>;
}
