// flow-typed signature: 7a6fbfc8c209b14733a9e9f98d4db2ec
// flow-typed version: <<STUB>>/csp-html-webpack-plugin_v^3.0.4/flow_v0.118.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'csp-html-webpack-plugin'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'csp-html-webpack-plugin' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'csp-html-webpack-plugin/jest.config' {
  declare module.exports: any;
}

declare module 'csp-html-webpack-plugin/plugin.jest' {
  declare module.exports: any;
}

declare module 'csp-html-webpack-plugin/plugin' {
  declare module.exports: any;
}

declare module 'csp-html-webpack-plugin/test-utils/fixtures/async' {
  declare module.exports: any;
}

declare module 'csp-html-webpack-plugin/test-utils/fixtures/common' {
  declare module.exports: any;
}

declare module 'csp-html-webpack-plugin/test-utils/fixtures' {
  declare module.exports: any;
}

declare module 'csp-html-webpack-plugin/test-utils/webpack-helpers' {
  declare module.exports: any;
}

// Filename aliases
declare module 'csp-html-webpack-plugin/jest.config.js' {
  declare module.exports: $Exports<'csp-html-webpack-plugin/jest.config'>;
}
declare module 'csp-html-webpack-plugin/plugin.jest.js' {
  declare module.exports: $Exports<'csp-html-webpack-plugin/plugin.jest'>;
}
declare module 'csp-html-webpack-plugin/plugin.js' {
  declare module.exports: $Exports<'csp-html-webpack-plugin/plugin'>;
}
declare module 'csp-html-webpack-plugin/test-utils/fixtures/async.js' {
  declare module.exports: $Exports<'csp-html-webpack-plugin/test-utils/fixtures/async'>;
}
declare module 'csp-html-webpack-plugin/test-utils/fixtures/common.js' {
  declare module.exports: $Exports<'csp-html-webpack-plugin/test-utils/fixtures/common'>;
}
declare module 'csp-html-webpack-plugin/test-utils/fixtures/index' {
  declare module.exports: $Exports<'csp-html-webpack-plugin/test-utils/fixtures'>;
}
declare module 'csp-html-webpack-plugin/test-utils/fixtures/index.js' {
  declare module.exports: $Exports<'csp-html-webpack-plugin/test-utils/fixtures'>;
}
declare module 'csp-html-webpack-plugin/test-utils/webpack-helpers.js' {
  declare module.exports: $Exports<'csp-html-webpack-plugin/test-utils/webpack-helpers'>;
}
