// flow-typed signature: 05463d9105167a728a04e1ff5201f635
// flow-typed version: <<STUB>>/easy-redux-undo_v^1.0.0/flow_v0.118.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'easy-redux-undo'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'easy-redux-undo' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'easy-redux-undo/lib' {
  declare module.exports: any;
}

// Filename aliases
declare module 'easy-redux-undo/lib/index' {
  declare module.exports: $Exports<'easy-redux-undo/lib'>;
}
declare module 'easy-redux-undo/lib/index.js' {
  declare module.exports: $Exports<'easy-redux-undo/lib'>;
}
