// flow-typed signature: a41cfa5b3901eaa3496788b0b425d260
// flow-typed version: <<STUB>>/fast-fuzzy_v^1.9.1/flow_v0.118.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'fast-fuzzy'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'fast-fuzzy' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'fast-fuzzy/lib/fuzzy' {
  declare module.exports: any;
}

// Filename aliases
declare module 'fast-fuzzy/lib/fuzzy.js' {
  declare module.exports: $Exports<'fast-fuzzy/lib/fuzzy'>;
}
