// flow-typed signature: 679934614fb6db38177fb201060c3fc7
// flow-typed version: <<STUB>>/styled-normalize_v^8.0.7/flow_v0.118.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'styled-normalize'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'styled-normalize' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'styled-normalize/dist' {
  declare module.exports: any;
}

// Filename aliases
declare module 'styled-normalize/dist/index' {
  declare module.exports: $Exports<'styled-normalize/dist'>;
}
declare module 'styled-normalize/dist/index.js' {
  declare module.exports: $Exports<'styled-normalize/dist'>;
}
