// flow-typed signature: 9f46e4a8dbd242a0cb9f72e10b687f20
// flow-typed version: <<STUB>>/@blueprintjs/core_v^3.23.1/flow_v0.118.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@blueprintjs/core'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@blueprintjs/core' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@blueprintjs/core/dist/core.bundle' {
  declare module.exports: any;
}

declare module '@blueprintjs/core/lib/cjs/accessibility/focusStyleManager' {
  declare module.exports: any;
}

declare module '@blueprintjs/core/lib/cjs/accessibility' {
  declare module.exports: any;
}

declare module '@blueprintjs/core/lib/cjs/common/abstractComponent' {
  declare module.exports: any;
}

declare module '@blueprintjs/core/lib/cjs/common/abstractComponent2' {
  declare module.exports: any;
}

declare module '@blueprintjs/core/lib/cjs/common/abstractPureComponent' {
  declare module.exports: any;
}

declare module '@blueprintjs/core/lib/cjs/common/abstractPureComponent2' {
  declare module.exports: any;
}

declare module '@blueprintjs/core/lib/cjs/common/alignment' {
  declare module.exports: any;
}

declare module '@blueprintjs/core/lib/cjs/common/boundary' {
  declare module.exports: any;
}

declare module '@blueprintjs/core/lib/cjs/common/classes' {
  declare module.exports: any;
}

declare module '@blueprintjs/core/lib/cjs/common/colors' {
  declare module.exports: any;
}

declare module '@blueprintjs/core/lib/cjs/common/configureDom4' {
  declare module.exports: any;
}

declare module '@blueprintjs/core/lib/cjs/common/constructor' {
  declare module.exports: any;
}

declare module '@blueprintjs/core/lib/cjs/common/elevation' {
  declare module.exports: any;
}

declare module '@blueprintjs/core/lib/cjs/common/errors' {
  declare module.exports: any;
}

declare module '@blueprintjs/core/lib/cjs/common' {
  declare module.exports: any;
}

declare module '@blueprintjs/core/lib/cjs/common/intent' {
  declare module.exports: any;
}

declare module '@blueprintjs/core/lib/cjs/common/interactionMode' {
  declare module.exports: any;
}

declare module '@blueprintjs/core/lib/cjs/common/keys' {
  declare module.exports: any;
}

declare module '@blueprintjs/core/lib/cjs/common/position' {
  declare module.exports: any;
}

declare module '@blueprintjs/core/lib/cjs/common/props' {
  declare module.exports: any;
}

declare module '@blueprintjs/core/lib/cjs/common/utils' {
  declare module.exports: any;
}

declare module '@blueprintjs/core/lib/cjs/common/utils/compareUtils' {
  declare module.exports: any;
}

declare module '@blueprintjs/core/lib/cjs/common/utils/isDarkTheme' {
  declare module.exports: any;
}

declare module '@blueprintjs/core/lib/cjs/common/utils/safeInvokeMember' {
  declare module.exports: any;
}

declare module '@blueprintjs/core/lib/cjs/compatibility/browser' {
  declare module.exports: any;
}

declare module '@blueprintjs/core/lib/cjs/compatibility' {
  declare module.exports: any;
}

declare module '@blueprintjs/core/lib/cjs/components/alert/alert' {
  declare module.exports: any;
}

declare module '@blueprintjs/core/lib/cjs/components/breadcrumbs/breadcrumb' {
  declare module.exports: any;
}

declare module '@blueprintjs/core/lib/cjs/components/breadcrumbs/breadcrumbs' {
  declare module.exports: any;
}

declare module '@blueprintjs/core/lib/cjs/components/button/abstractButton' {
  declare module.exports: any;
}

declare module '@blueprintjs/core/lib/cjs/components/button/buttonGroup' {
  declare module.exports: any;
}

declare module '@blueprintjs/core/lib/cjs/components/button/buttons' {
  declare module.exports: any;
}

declare module '@blueprintjs/core/lib/cjs/components/callout/callout' {
  declare module.exports: any;
}

declare module '@blueprintjs/core/lib/cjs/components/card/card' {
  declare module.exports: any;
}

declare module '@blueprintjs/core/lib/cjs/components/collapse/collapse' {
  declare module.exports: any;
}

declare module '@blueprintjs/core/lib/cjs/components/collapsible-list/collapsibleList' {
  declare module.exports: any;
}

declare module '@blueprintjs/core/lib/cjs/components/context-menu/contextMenu' {
  declare module.exports: any;
}

declare module '@blueprintjs/core/lib/cjs/components/context-menu/contextMenuTarget' {
  declare module.exports: any;
}

declare module '@blueprintjs/core/lib/cjs/components/dialog/dialog' {
  declare module.exports: any;
}

declare module '@blueprintjs/core/lib/cjs/components/divider/divider' {
  declare module.exports: any;
}

declare module '@blueprintjs/core/lib/cjs/components/drawer/drawer' {
  declare module.exports: any;
}

declare module '@blueprintjs/core/lib/cjs/components/editable-text/editableText' {
  declare module.exports: any;
}

declare module '@blueprintjs/core/lib/cjs/components/forms/controlGroup' {
  declare module.exports: any;
}

declare module '@blueprintjs/core/lib/cjs/components/forms/controls' {
  declare module.exports: any;
}

declare module '@blueprintjs/core/lib/cjs/components/forms/fileInput' {
  declare module.exports: any;
}

declare module '@blueprintjs/core/lib/cjs/components/forms/formGroup' {
  declare module.exports: any;
}

declare module '@blueprintjs/core/lib/cjs/components/forms/inputGroup' {
  declare module.exports: any;
}

declare module '@blueprintjs/core/lib/cjs/components/forms/numericInput' {
  declare module.exports: any;
}

declare module '@blueprintjs/core/lib/cjs/components/forms/numericInputUtils' {
  declare module.exports: any;
}

declare module '@blueprintjs/core/lib/cjs/components/forms/radioGroup' {
  declare module.exports: any;
}

declare module '@blueprintjs/core/lib/cjs/components/forms/textArea' {
  declare module.exports: any;
}

declare module '@blueprintjs/core/lib/cjs/components/hotkeys/hotkey' {
  declare module.exports: any;
}

declare module '@blueprintjs/core/lib/cjs/components/hotkeys/hotkeyParser' {
  declare module.exports: any;
}

declare module '@blueprintjs/core/lib/cjs/components/hotkeys/hotkeys' {
  declare module.exports: any;
}

declare module '@blueprintjs/core/lib/cjs/components/hotkeys/hotkeysDialog' {
  declare module.exports: any;
}

declare module '@blueprintjs/core/lib/cjs/components/hotkeys/hotkeysEvents' {
  declare module.exports: any;
}

declare module '@blueprintjs/core/lib/cjs/components/hotkeys/hotkeysTarget' {
  declare module.exports: any;
}

declare module '@blueprintjs/core/lib/cjs/components/hotkeys/keyCombo' {
  declare module.exports: any;
}

declare module '@blueprintjs/core/lib/cjs/components/html-select/htmlSelect' {
  declare module.exports: any;
}

declare module '@blueprintjs/core/lib/cjs/components/html-table/htmlTable' {
  declare module.exports: any;
}

declare module '@blueprintjs/core/lib/cjs/components/html/html' {
  declare module.exports: any;
}

declare module '@blueprintjs/core/lib/cjs/components/icon/icon' {
  declare module.exports: any;
}

declare module '@blueprintjs/core/lib/cjs/components' {
  declare module.exports: any;
}

declare module '@blueprintjs/core/lib/cjs/components/menu/menu' {
  declare module.exports: any;
}

declare module '@blueprintjs/core/lib/cjs/components/menu/menuDivider' {
  declare module.exports: any;
}

declare module '@blueprintjs/core/lib/cjs/components/menu/menuItem' {
  declare module.exports: any;
}

declare module '@blueprintjs/core/lib/cjs/components/navbar/navbar' {
  declare module.exports: any;
}

declare module '@blueprintjs/core/lib/cjs/components/navbar/navbarDivider' {
  declare module.exports: any;
}

declare module '@blueprintjs/core/lib/cjs/components/navbar/navbarGroup' {
  declare module.exports: any;
}

declare module '@blueprintjs/core/lib/cjs/components/navbar/navbarHeading' {
  declare module.exports: any;
}

declare module '@blueprintjs/core/lib/cjs/components/non-ideal-state/nonIdealState' {
  declare module.exports: any;
}

declare module '@blueprintjs/core/lib/cjs/components/overflow-list/overflowList' {
  declare module.exports: any;
}

declare module '@blueprintjs/core/lib/cjs/components/overlay/overlay' {
  declare module.exports: any;
}

declare module '@blueprintjs/core/lib/cjs/components/panel-stack/panelProps' {
  declare module.exports: any;
}

declare module '@blueprintjs/core/lib/cjs/components/panel-stack/panelStack' {
  declare module.exports: any;
}

declare module '@blueprintjs/core/lib/cjs/components/panel-stack/panelView' {
  declare module.exports: any;
}

declare module '@blueprintjs/core/lib/cjs/components/popover/popover' {
  declare module.exports: any;
}

declare module '@blueprintjs/core/lib/cjs/components/popover/popoverArrow' {
  declare module.exports: any;
}

declare module '@blueprintjs/core/lib/cjs/components/popover/popoverMigrationUtils' {
  declare module.exports: any;
}

declare module '@blueprintjs/core/lib/cjs/components/popover/popoverSharedProps' {
  declare module.exports: any;
}

declare module '@blueprintjs/core/lib/cjs/components/popover/popperUtils' {
  declare module.exports: any;
}

declare module '@blueprintjs/core/lib/cjs/components/portal/portal' {
  declare module.exports: any;
}

declare module '@blueprintjs/core/lib/cjs/components/progress-bar/progressBar' {
  declare module.exports: any;
}

declare module '@blueprintjs/core/lib/cjs/components/resize-sensor/resizeSensor' {
  declare module.exports: any;
}

declare module '@blueprintjs/core/lib/cjs/components/slider/handle' {
  declare module.exports: any;
}

declare module '@blueprintjs/core/lib/cjs/components/slider/handleProps' {
  declare module.exports: any;
}

declare module '@blueprintjs/core/lib/cjs/components/slider/multiSlider' {
  declare module.exports: any;
}

declare module '@blueprintjs/core/lib/cjs/components/slider/rangeSlider' {
  declare module.exports: any;
}

declare module '@blueprintjs/core/lib/cjs/components/slider/slider' {
  declare module.exports: any;
}

declare module '@blueprintjs/core/lib/cjs/components/slider/sliderUtils' {
  declare module.exports: any;
}

declare module '@blueprintjs/core/lib/cjs/components/spinner/spinner' {
  declare module.exports: any;
}

declare module '@blueprintjs/core/lib/cjs/components/tabs/tab' {
  declare module.exports: any;
}

declare module '@blueprintjs/core/lib/cjs/components/tabs/tabs' {
  declare module.exports: any;
}

declare module '@blueprintjs/core/lib/cjs/components/tabs/tabTitle' {
  declare module.exports: any;
}

declare module '@blueprintjs/core/lib/cjs/components/tag-input/tagInput' {
  declare module.exports: any;
}

declare module '@blueprintjs/core/lib/cjs/components/tag/tag' {
  declare module.exports: any;
}

declare module '@blueprintjs/core/lib/cjs/components/text/text' {
  declare module.exports: any;
}

declare module '@blueprintjs/core/lib/cjs/components/toast/toast' {
  declare module.exports: any;
}

declare module '@blueprintjs/core/lib/cjs/components/toast/toaster' {
  declare module.exports: any;
}

declare module '@blueprintjs/core/lib/cjs/components/tooltip/tooltip' {
  declare module.exports: any;
}

declare module '@blueprintjs/core/lib/cjs/components/tree/tree' {
  declare module.exports: any;
}

declare module '@blueprintjs/core/lib/cjs/components/tree/treeNode' {
  declare module.exports: any;
}

declare module '@blueprintjs/core/lib/cjs' {
  declare module.exports: any;
}

declare module '@blueprintjs/core/lib/esm/accessibility/focusStyleManager' {
  declare module.exports: any;
}

declare module '@blueprintjs/core/lib/esm/accessibility' {
  declare module.exports: any;
}

declare module '@blueprintjs/core/lib/esm/common/abstractComponent' {
  declare module.exports: any;
}

declare module '@blueprintjs/core/lib/esm/common/abstractComponent2' {
  declare module.exports: any;
}

declare module '@blueprintjs/core/lib/esm/common/abstractPureComponent' {
  declare module.exports: any;
}

declare module '@blueprintjs/core/lib/esm/common/abstractPureComponent2' {
  declare module.exports: any;
}

declare module '@blueprintjs/core/lib/esm/common/alignment' {
  declare module.exports: any;
}

declare module '@blueprintjs/core/lib/esm/common/boundary' {
  declare module.exports: any;
}

declare module '@blueprintjs/core/lib/esm/common/classes' {
  declare module.exports: any;
}

declare module '@blueprintjs/core/lib/esm/common/colors' {
  declare module.exports: any;
}

declare module '@blueprintjs/core/lib/esm/common/configureDom4' {
  declare module.exports: any;
}

declare module '@blueprintjs/core/lib/esm/common/constructor' {
  declare module.exports: any;
}

declare module '@blueprintjs/core/lib/esm/common/elevation' {
  declare module.exports: any;
}

declare module '@blueprintjs/core/lib/esm/common/errors' {
  declare module.exports: any;
}

declare module '@blueprintjs/core/lib/esm/common' {
  declare module.exports: any;
}

declare module '@blueprintjs/core/lib/esm/common/intent' {
  declare module.exports: any;
}

declare module '@blueprintjs/core/lib/esm/common/interactionMode' {
  declare module.exports: any;
}

declare module '@blueprintjs/core/lib/esm/common/keys' {
  declare module.exports: any;
}

declare module '@blueprintjs/core/lib/esm/common/position' {
  declare module.exports: any;
}

declare module '@blueprintjs/core/lib/esm/common/props' {
  declare module.exports: any;
}

declare module '@blueprintjs/core/lib/esm/common/utils' {
  declare module.exports: any;
}

declare module '@blueprintjs/core/lib/esm/common/utils/compareUtils' {
  declare module.exports: any;
}

declare module '@blueprintjs/core/lib/esm/common/utils/isDarkTheme' {
  declare module.exports: any;
}

declare module '@blueprintjs/core/lib/esm/common/utils/safeInvokeMember' {
  declare module.exports: any;
}

declare module '@blueprintjs/core/lib/esm/compatibility/browser' {
  declare module.exports: any;
}

declare module '@blueprintjs/core/lib/esm/compatibility' {
  declare module.exports: any;
}

declare module '@blueprintjs/core/lib/esm/components/alert/alert' {
  declare module.exports: any;
}

declare module '@blueprintjs/core/lib/esm/components/breadcrumbs/breadcrumb' {
  declare module.exports: any;
}

declare module '@blueprintjs/core/lib/esm/components/breadcrumbs/breadcrumbs' {
  declare module.exports: any;
}

declare module '@blueprintjs/core/lib/esm/components/button/abstractButton' {
  declare module.exports: any;
}

declare module '@blueprintjs/core/lib/esm/components/button/buttonGroup' {
  declare module.exports: any;
}

declare module '@blueprintjs/core/lib/esm/components/button/buttons' {
  declare module.exports: any;
}

declare module '@blueprintjs/core/lib/esm/components/callout/callout' {
  declare module.exports: any;
}

declare module '@blueprintjs/core/lib/esm/components/card/card' {
  declare module.exports: any;
}

declare module '@blueprintjs/core/lib/esm/components/collapse/collapse' {
  declare module.exports: any;
}

declare module '@blueprintjs/core/lib/esm/components/collapsible-list/collapsibleList' {
  declare module.exports: any;
}

declare module '@blueprintjs/core/lib/esm/components/context-menu/contextMenu' {
  declare module.exports: any;
}

declare module '@blueprintjs/core/lib/esm/components/context-menu/contextMenuTarget' {
  declare module.exports: any;
}

declare module '@blueprintjs/core/lib/esm/components/dialog/dialog' {
  declare module.exports: any;
}

declare module '@blueprintjs/core/lib/esm/components/divider/divider' {
  declare module.exports: any;
}

declare module '@blueprintjs/core/lib/esm/components/drawer/drawer' {
  declare module.exports: any;
}

declare module '@blueprintjs/core/lib/esm/components/editable-text/editableText' {
  declare module.exports: any;
}

declare module '@blueprintjs/core/lib/esm/components/forms/controlGroup' {
  declare module.exports: any;
}

declare module '@blueprintjs/core/lib/esm/components/forms/controls' {
  declare module.exports: any;
}

declare module '@blueprintjs/core/lib/esm/components/forms/fileInput' {
  declare module.exports: any;
}

declare module '@blueprintjs/core/lib/esm/components/forms/formGroup' {
  declare module.exports: any;
}

declare module '@blueprintjs/core/lib/esm/components/forms/inputGroup' {
  declare module.exports: any;
}

declare module '@blueprintjs/core/lib/esm/components/forms/numericInput' {
  declare module.exports: any;
}

declare module '@blueprintjs/core/lib/esm/components/forms/numericInputUtils' {
  declare module.exports: any;
}

declare module '@blueprintjs/core/lib/esm/components/forms/radioGroup' {
  declare module.exports: any;
}

declare module '@blueprintjs/core/lib/esm/components/forms/textArea' {
  declare module.exports: any;
}

declare module '@blueprintjs/core/lib/esm/components/hotkeys/hotkey' {
  declare module.exports: any;
}

declare module '@blueprintjs/core/lib/esm/components/hotkeys/hotkeyParser' {
  declare module.exports: any;
}

declare module '@blueprintjs/core/lib/esm/components/hotkeys/hotkeys' {
  declare module.exports: any;
}

declare module '@blueprintjs/core/lib/esm/components/hotkeys/hotkeysDialog' {
  declare module.exports: any;
}

declare module '@blueprintjs/core/lib/esm/components/hotkeys/hotkeysEvents' {
  declare module.exports: any;
}

declare module '@blueprintjs/core/lib/esm/components/hotkeys/hotkeysTarget' {
  declare module.exports: any;
}

declare module '@blueprintjs/core/lib/esm/components/hotkeys/keyCombo' {
  declare module.exports: any;
}

declare module '@blueprintjs/core/lib/esm/components/html-select/htmlSelect' {
  declare module.exports: any;
}

declare module '@blueprintjs/core/lib/esm/components/html-table/htmlTable' {
  declare module.exports: any;
}

declare module '@blueprintjs/core/lib/esm/components/html/html' {
  declare module.exports: any;
}

declare module '@blueprintjs/core/lib/esm/components/icon/icon' {
  declare module.exports: any;
}

declare module '@blueprintjs/core/lib/esm/components' {
  declare module.exports: any;
}

declare module '@blueprintjs/core/lib/esm/components/menu/menu' {
  declare module.exports: any;
}

declare module '@blueprintjs/core/lib/esm/components/menu/menuDivider' {
  declare module.exports: any;
}

declare module '@blueprintjs/core/lib/esm/components/menu/menuItem' {
  declare module.exports: any;
}

declare module '@blueprintjs/core/lib/esm/components/navbar/navbar' {
  declare module.exports: any;
}

declare module '@blueprintjs/core/lib/esm/components/navbar/navbarDivider' {
  declare module.exports: any;
}

declare module '@blueprintjs/core/lib/esm/components/navbar/navbarGroup' {
  declare module.exports: any;
}

declare module '@blueprintjs/core/lib/esm/components/navbar/navbarHeading' {
  declare module.exports: any;
}

declare module '@blueprintjs/core/lib/esm/components/non-ideal-state/nonIdealState' {
  declare module.exports: any;
}

declare module '@blueprintjs/core/lib/esm/components/overflow-list/overflowList' {
  declare module.exports: any;
}

declare module '@blueprintjs/core/lib/esm/components/overlay/overlay' {
  declare module.exports: any;
}

declare module '@blueprintjs/core/lib/esm/components/panel-stack/panelProps' {
  declare module.exports: any;
}

declare module '@blueprintjs/core/lib/esm/components/panel-stack/panelStack' {
  declare module.exports: any;
}

declare module '@blueprintjs/core/lib/esm/components/panel-stack/panelView' {
  declare module.exports: any;
}

declare module '@blueprintjs/core/lib/esm/components/popover/popover' {
  declare module.exports: any;
}

declare module '@blueprintjs/core/lib/esm/components/popover/popoverArrow' {
  declare module.exports: any;
}

declare module '@blueprintjs/core/lib/esm/components/popover/popoverMigrationUtils' {
  declare module.exports: any;
}

declare module '@blueprintjs/core/lib/esm/components/popover/popoverSharedProps' {
  declare module.exports: any;
}

declare module '@blueprintjs/core/lib/esm/components/popover/popperUtils' {
  declare module.exports: any;
}

declare module '@blueprintjs/core/lib/esm/components/portal/portal' {
  declare module.exports: any;
}

declare module '@blueprintjs/core/lib/esm/components/progress-bar/progressBar' {
  declare module.exports: any;
}

declare module '@blueprintjs/core/lib/esm/components/resize-sensor/resizeSensor' {
  declare module.exports: any;
}

declare module '@blueprintjs/core/lib/esm/components/slider/handle' {
  declare module.exports: any;
}

declare module '@blueprintjs/core/lib/esm/components/slider/handleProps' {
  declare module.exports: any;
}

declare module '@blueprintjs/core/lib/esm/components/slider/multiSlider' {
  declare module.exports: any;
}

declare module '@blueprintjs/core/lib/esm/components/slider/rangeSlider' {
  declare module.exports: any;
}

declare module '@blueprintjs/core/lib/esm/components/slider/slider' {
  declare module.exports: any;
}

declare module '@blueprintjs/core/lib/esm/components/slider/sliderUtils' {
  declare module.exports: any;
}

declare module '@blueprintjs/core/lib/esm/components/spinner/spinner' {
  declare module.exports: any;
}

declare module '@blueprintjs/core/lib/esm/components/tabs/tab' {
  declare module.exports: any;
}

declare module '@blueprintjs/core/lib/esm/components/tabs/tabs' {
  declare module.exports: any;
}

declare module '@blueprintjs/core/lib/esm/components/tabs/tabTitle' {
  declare module.exports: any;
}

declare module '@blueprintjs/core/lib/esm/components/tag-input/tagInput' {
  declare module.exports: any;
}

declare module '@blueprintjs/core/lib/esm/components/tag/tag' {
  declare module.exports: any;
}

declare module '@blueprintjs/core/lib/esm/components/text/text' {
  declare module.exports: any;
}

declare module '@blueprintjs/core/lib/esm/components/toast/toast' {
  declare module.exports: any;
}

declare module '@blueprintjs/core/lib/esm/components/toast/toaster' {
  declare module.exports: any;
}

declare module '@blueprintjs/core/lib/esm/components/tooltip/tooltip' {
  declare module.exports: any;
}

declare module '@blueprintjs/core/lib/esm/components/tree/tree' {
  declare module.exports: any;
}

declare module '@blueprintjs/core/lib/esm/components/tree/treeNode' {
  declare module.exports: any;
}

declare module '@blueprintjs/core/lib/esm' {
  declare module.exports: any;
}

declare module '@blueprintjs/core/lib/esnext/accessibility/focusStyleManager' {
  declare module.exports: any;
}

declare module '@blueprintjs/core/lib/esnext/accessibility' {
  declare module.exports: any;
}

declare module '@blueprintjs/core/lib/esnext/common/abstractComponent' {
  declare module.exports: any;
}

declare module '@blueprintjs/core/lib/esnext/common/abstractComponent2' {
  declare module.exports: any;
}

declare module '@blueprintjs/core/lib/esnext/common/abstractPureComponent' {
  declare module.exports: any;
}

declare module '@blueprintjs/core/lib/esnext/common/abstractPureComponent2' {
  declare module.exports: any;
}

declare module '@blueprintjs/core/lib/esnext/common/alignment' {
  declare module.exports: any;
}

declare module '@blueprintjs/core/lib/esnext/common/boundary' {
  declare module.exports: any;
}

declare module '@blueprintjs/core/lib/esnext/common/classes' {
  declare module.exports: any;
}

declare module '@blueprintjs/core/lib/esnext/common/colors' {
  declare module.exports: any;
}

declare module '@blueprintjs/core/lib/esnext/common/configureDom4' {
  declare module.exports: any;
}

declare module '@blueprintjs/core/lib/esnext/common/constructor' {
  declare module.exports: any;
}

declare module '@blueprintjs/core/lib/esnext/common/elevation' {
  declare module.exports: any;
}

declare module '@blueprintjs/core/lib/esnext/common/errors' {
  declare module.exports: any;
}

declare module '@blueprintjs/core/lib/esnext/common' {
  declare module.exports: any;
}

declare module '@blueprintjs/core/lib/esnext/common/intent' {
  declare module.exports: any;
}

declare module '@blueprintjs/core/lib/esnext/common/interactionMode' {
  declare module.exports: any;
}

declare module '@blueprintjs/core/lib/esnext/common/keys' {
  declare module.exports: any;
}

declare module '@blueprintjs/core/lib/esnext/common/position' {
  declare module.exports: any;
}

declare module '@blueprintjs/core/lib/esnext/common/props' {
  declare module.exports: any;
}

declare module '@blueprintjs/core/lib/esnext/common/utils' {
  declare module.exports: any;
}

declare module '@blueprintjs/core/lib/esnext/common/utils/compareUtils' {
  declare module.exports: any;
}

declare module '@blueprintjs/core/lib/esnext/common/utils/isDarkTheme' {
  declare module.exports: any;
}

declare module '@blueprintjs/core/lib/esnext/common/utils/safeInvokeMember' {
  declare module.exports: any;
}

declare module '@blueprintjs/core/lib/esnext/compatibility/browser' {
  declare module.exports: any;
}

declare module '@blueprintjs/core/lib/esnext/compatibility' {
  declare module.exports: any;
}

declare module '@blueprintjs/core/lib/esnext/components/alert/alert' {
  declare module.exports: any;
}

declare module '@blueprintjs/core/lib/esnext/components/breadcrumbs/breadcrumb' {
  declare module.exports: any;
}

declare module '@blueprintjs/core/lib/esnext/components/breadcrumbs/breadcrumbs' {
  declare module.exports: any;
}

declare module '@blueprintjs/core/lib/esnext/components/button/abstractButton' {
  declare module.exports: any;
}

declare module '@blueprintjs/core/lib/esnext/components/button/buttonGroup' {
  declare module.exports: any;
}

declare module '@blueprintjs/core/lib/esnext/components/button/buttons' {
  declare module.exports: any;
}

declare module '@blueprintjs/core/lib/esnext/components/callout/callout' {
  declare module.exports: any;
}

declare module '@blueprintjs/core/lib/esnext/components/card/card' {
  declare module.exports: any;
}

declare module '@blueprintjs/core/lib/esnext/components/collapse/collapse' {
  declare module.exports: any;
}

declare module '@blueprintjs/core/lib/esnext/components/collapsible-list/collapsibleList' {
  declare module.exports: any;
}

declare module '@blueprintjs/core/lib/esnext/components/context-menu/contextMenu' {
  declare module.exports: any;
}

declare module '@blueprintjs/core/lib/esnext/components/context-menu/contextMenuTarget' {
  declare module.exports: any;
}

declare module '@blueprintjs/core/lib/esnext/components/dialog/dialog' {
  declare module.exports: any;
}

declare module '@blueprintjs/core/lib/esnext/components/divider/divider' {
  declare module.exports: any;
}

declare module '@blueprintjs/core/lib/esnext/components/drawer/drawer' {
  declare module.exports: any;
}

declare module '@blueprintjs/core/lib/esnext/components/editable-text/editableText' {
  declare module.exports: any;
}

declare module '@blueprintjs/core/lib/esnext/components/forms/controlGroup' {
  declare module.exports: any;
}

declare module '@blueprintjs/core/lib/esnext/components/forms/controls' {
  declare module.exports: any;
}

declare module '@blueprintjs/core/lib/esnext/components/forms/fileInput' {
  declare module.exports: any;
}

declare module '@blueprintjs/core/lib/esnext/components/forms/formGroup' {
  declare module.exports: any;
}

declare module '@blueprintjs/core/lib/esnext/components/forms/inputGroup' {
  declare module.exports: any;
}

declare module '@blueprintjs/core/lib/esnext/components/forms/numericInput' {
  declare module.exports: any;
}

declare module '@blueprintjs/core/lib/esnext/components/forms/numericInputUtils' {
  declare module.exports: any;
}

declare module '@blueprintjs/core/lib/esnext/components/forms/radioGroup' {
  declare module.exports: any;
}

declare module '@blueprintjs/core/lib/esnext/components/forms/textArea' {
  declare module.exports: any;
}

declare module '@blueprintjs/core/lib/esnext/components/hotkeys/hotkey' {
  declare module.exports: any;
}

declare module '@blueprintjs/core/lib/esnext/components/hotkeys/hotkeyParser' {
  declare module.exports: any;
}

declare module '@blueprintjs/core/lib/esnext/components/hotkeys/hotkeys' {
  declare module.exports: any;
}

declare module '@blueprintjs/core/lib/esnext/components/hotkeys/hotkeysDialog' {
  declare module.exports: any;
}

declare module '@blueprintjs/core/lib/esnext/components/hotkeys/hotkeysEvents' {
  declare module.exports: any;
}

declare module '@blueprintjs/core/lib/esnext/components/hotkeys/hotkeysTarget' {
  declare module.exports: any;
}

declare module '@blueprintjs/core/lib/esnext/components/hotkeys/keyCombo' {
  declare module.exports: any;
}

declare module '@blueprintjs/core/lib/esnext/components/html-select/htmlSelect' {
  declare module.exports: any;
}

declare module '@blueprintjs/core/lib/esnext/components/html-table/htmlTable' {
  declare module.exports: any;
}

declare module '@blueprintjs/core/lib/esnext/components/html/html' {
  declare module.exports: any;
}

declare module '@blueprintjs/core/lib/esnext/components/icon/icon' {
  declare module.exports: any;
}

declare module '@blueprintjs/core/lib/esnext/components' {
  declare module.exports: any;
}

declare module '@blueprintjs/core/lib/esnext/components/menu/menu' {
  declare module.exports: any;
}

declare module '@blueprintjs/core/lib/esnext/components/menu/menuDivider' {
  declare module.exports: any;
}

declare module '@blueprintjs/core/lib/esnext/components/menu/menuItem' {
  declare module.exports: any;
}

declare module '@blueprintjs/core/lib/esnext/components/navbar/navbar' {
  declare module.exports: any;
}

declare module '@blueprintjs/core/lib/esnext/components/navbar/navbarDivider' {
  declare module.exports: any;
}

declare module '@blueprintjs/core/lib/esnext/components/navbar/navbarGroup' {
  declare module.exports: any;
}

declare module '@blueprintjs/core/lib/esnext/components/navbar/navbarHeading' {
  declare module.exports: any;
}

declare module '@blueprintjs/core/lib/esnext/components/non-ideal-state/nonIdealState' {
  declare module.exports: any;
}

declare module '@blueprintjs/core/lib/esnext/components/overflow-list/overflowList' {
  declare module.exports: any;
}

declare module '@blueprintjs/core/lib/esnext/components/overlay/overlay' {
  declare module.exports: any;
}

declare module '@blueprintjs/core/lib/esnext/components/panel-stack/panelProps' {
  declare module.exports: any;
}

declare module '@blueprintjs/core/lib/esnext/components/panel-stack/panelStack' {
  declare module.exports: any;
}

declare module '@blueprintjs/core/lib/esnext/components/panel-stack/panelView' {
  declare module.exports: any;
}

declare module '@blueprintjs/core/lib/esnext/components/popover/popover' {
  declare module.exports: any;
}

declare module '@blueprintjs/core/lib/esnext/components/popover/popoverArrow' {
  declare module.exports: any;
}

declare module '@blueprintjs/core/lib/esnext/components/popover/popoverMigrationUtils' {
  declare module.exports: any;
}

declare module '@blueprintjs/core/lib/esnext/components/popover/popoverSharedProps' {
  declare module.exports: any;
}

declare module '@blueprintjs/core/lib/esnext/components/popover/popperUtils' {
  declare module.exports: any;
}

declare module '@blueprintjs/core/lib/esnext/components/portal/portal' {
  declare module.exports: any;
}

declare module '@blueprintjs/core/lib/esnext/components/progress-bar/progressBar' {
  declare module.exports: any;
}

declare module '@blueprintjs/core/lib/esnext/components/resize-sensor/resizeSensor' {
  declare module.exports: any;
}

declare module '@blueprintjs/core/lib/esnext/components/slider/handle' {
  declare module.exports: any;
}

declare module '@blueprintjs/core/lib/esnext/components/slider/handleProps' {
  declare module.exports: any;
}

declare module '@blueprintjs/core/lib/esnext/components/slider/multiSlider' {
  declare module.exports: any;
}

declare module '@blueprintjs/core/lib/esnext/components/slider/rangeSlider' {
  declare module.exports: any;
}

declare module '@blueprintjs/core/lib/esnext/components/slider/slider' {
  declare module.exports: any;
}

declare module '@blueprintjs/core/lib/esnext/components/slider/sliderUtils' {
  declare module.exports: any;
}

declare module '@blueprintjs/core/lib/esnext/components/spinner/spinner' {
  declare module.exports: any;
}

declare module '@blueprintjs/core/lib/esnext/components/tabs/tab' {
  declare module.exports: any;
}

declare module '@blueprintjs/core/lib/esnext/components/tabs/tabs' {
  declare module.exports: any;
}

declare module '@blueprintjs/core/lib/esnext/components/tabs/tabTitle' {
  declare module.exports: any;
}

declare module '@blueprintjs/core/lib/esnext/components/tag-input/tagInput' {
  declare module.exports: any;
}

declare module '@blueprintjs/core/lib/esnext/components/tag/tag' {
  declare module.exports: any;
}

declare module '@blueprintjs/core/lib/esnext/components/text/text' {
  declare module.exports: any;
}

declare module '@blueprintjs/core/lib/esnext/components/toast/toast' {
  declare module.exports: any;
}

declare module '@blueprintjs/core/lib/esnext/components/toast/toaster' {
  declare module.exports: any;
}

declare module '@blueprintjs/core/lib/esnext/components/tooltip/tooltip' {
  declare module.exports: any;
}

declare module '@blueprintjs/core/lib/esnext/components/tree/tree' {
  declare module.exports: any;
}

declare module '@blueprintjs/core/lib/esnext/components/tree/treeNode' {
  declare module.exports: any;
}

declare module '@blueprintjs/core/lib/esnext' {
  declare module.exports: any;
}

declare module '@blueprintjs/core/scripts/sass-custom-functions' {
  declare module.exports: any;
}

// Filename aliases
declare module '@blueprintjs/core/dist/core.bundle.js' {
  declare module.exports: $Exports<'@blueprintjs/core/dist/core.bundle'>;
}
declare module '@blueprintjs/core/lib/cjs/accessibility/focusStyleManager.js' {
  declare module.exports: $Exports<'@blueprintjs/core/lib/cjs/accessibility/focusStyleManager'>;
}
declare module '@blueprintjs/core/lib/cjs/accessibility/index' {
  declare module.exports: $Exports<'@blueprintjs/core/lib/cjs/accessibility'>;
}
declare module '@blueprintjs/core/lib/cjs/accessibility/index.js' {
  declare module.exports: $Exports<'@blueprintjs/core/lib/cjs/accessibility'>;
}
declare module '@blueprintjs/core/lib/cjs/common/abstractComponent.js' {
  declare module.exports: $Exports<'@blueprintjs/core/lib/cjs/common/abstractComponent'>;
}
declare module '@blueprintjs/core/lib/cjs/common/abstractComponent2.js' {
  declare module.exports: $Exports<'@blueprintjs/core/lib/cjs/common/abstractComponent2'>;
}
declare module '@blueprintjs/core/lib/cjs/common/abstractPureComponent.js' {
  declare module.exports: $Exports<'@blueprintjs/core/lib/cjs/common/abstractPureComponent'>;
}
declare module '@blueprintjs/core/lib/cjs/common/abstractPureComponent2.js' {
  declare module.exports: $Exports<'@blueprintjs/core/lib/cjs/common/abstractPureComponent2'>;
}
declare module '@blueprintjs/core/lib/cjs/common/alignment.js' {
  declare module.exports: $Exports<'@blueprintjs/core/lib/cjs/common/alignment'>;
}
declare module '@blueprintjs/core/lib/cjs/common/boundary.js' {
  declare module.exports: $Exports<'@blueprintjs/core/lib/cjs/common/boundary'>;
}
declare module '@blueprintjs/core/lib/cjs/common/classes.js' {
  declare module.exports: $Exports<'@blueprintjs/core/lib/cjs/common/classes'>;
}
declare module '@blueprintjs/core/lib/cjs/common/colors.js' {
  declare module.exports: $Exports<'@blueprintjs/core/lib/cjs/common/colors'>;
}
declare module '@blueprintjs/core/lib/cjs/common/configureDom4.js' {
  declare module.exports: $Exports<'@blueprintjs/core/lib/cjs/common/configureDom4'>;
}
declare module '@blueprintjs/core/lib/cjs/common/constructor.js' {
  declare module.exports: $Exports<'@blueprintjs/core/lib/cjs/common/constructor'>;
}
declare module '@blueprintjs/core/lib/cjs/common/elevation.js' {
  declare module.exports: $Exports<'@blueprintjs/core/lib/cjs/common/elevation'>;
}
declare module '@blueprintjs/core/lib/cjs/common/errors.js' {
  declare module.exports: $Exports<'@blueprintjs/core/lib/cjs/common/errors'>;
}
declare module '@blueprintjs/core/lib/cjs/common/index' {
  declare module.exports: $Exports<'@blueprintjs/core/lib/cjs/common'>;
}
declare module '@blueprintjs/core/lib/cjs/common/index.js' {
  declare module.exports: $Exports<'@blueprintjs/core/lib/cjs/common'>;
}
declare module '@blueprintjs/core/lib/cjs/common/intent.js' {
  declare module.exports: $Exports<'@blueprintjs/core/lib/cjs/common/intent'>;
}
declare module '@blueprintjs/core/lib/cjs/common/interactionMode.js' {
  declare module.exports: $Exports<'@blueprintjs/core/lib/cjs/common/interactionMode'>;
}
declare module '@blueprintjs/core/lib/cjs/common/keys.js' {
  declare module.exports: $Exports<'@blueprintjs/core/lib/cjs/common/keys'>;
}
declare module '@blueprintjs/core/lib/cjs/common/position.js' {
  declare module.exports: $Exports<'@blueprintjs/core/lib/cjs/common/position'>;
}
declare module '@blueprintjs/core/lib/cjs/common/props.js' {
  declare module.exports: $Exports<'@blueprintjs/core/lib/cjs/common/props'>;
}
declare module '@blueprintjs/core/lib/cjs/common/utils.js' {
  declare module.exports: $Exports<'@blueprintjs/core/lib/cjs/common/utils'>;
}
declare module '@blueprintjs/core/lib/cjs/common/utils/compareUtils.js' {
  declare module.exports: $Exports<'@blueprintjs/core/lib/cjs/common/utils/compareUtils'>;
}
declare module '@blueprintjs/core/lib/cjs/common/utils/isDarkTheme.js' {
  declare module.exports: $Exports<'@blueprintjs/core/lib/cjs/common/utils/isDarkTheme'>;
}
declare module '@blueprintjs/core/lib/cjs/common/utils/safeInvokeMember.js' {
  declare module.exports: $Exports<'@blueprintjs/core/lib/cjs/common/utils/safeInvokeMember'>;
}
declare module '@blueprintjs/core/lib/cjs/compatibility/browser.js' {
  declare module.exports: $Exports<'@blueprintjs/core/lib/cjs/compatibility/browser'>;
}
declare module '@blueprintjs/core/lib/cjs/compatibility/index' {
  declare module.exports: $Exports<'@blueprintjs/core/lib/cjs/compatibility'>;
}
declare module '@blueprintjs/core/lib/cjs/compatibility/index.js' {
  declare module.exports: $Exports<'@blueprintjs/core/lib/cjs/compatibility'>;
}
declare module '@blueprintjs/core/lib/cjs/components/alert/alert.js' {
  declare module.exports: $Exports<'@blueprintjs/core/lib/cjs/components/alert/alert'>;
}
declare module '@blueprintjs/core/lib/cjs/components/breadcrumbs/breadcrumb.js' {
  declare module.exports: $Exports<'@blueprintjs/core/lib/cjs/components/breadcrumbs/breadcrumb'>;
}
declare module '@blueprintjs/core/lib/cjs/components/breadcrumbs/breadcrumbs.js' {
  declare module.exports: $Exports<'@blueprintjs/core/lib/cjs/components/breadcrumbs/breadcrumbs'>;
}
declare module '@blueprintjs/core/lib/cjs/components/button/abstractButton.js' {
  declare module.exports: $Exports<'@blueprintjs/core/lib/cjs/components/button/abstractButton'>;
}
declare module '@blueprintjs/core/lib/cjs/components/button/buttonGroup.js' {
  declare module.exports: $Exports<'@blueprintjs/core/lib/cjs/components/button/buttonGroup'>;
}
declare module '@blueprintjs/core/lib/cjs/components/button/buttons.js' {
  declare module.exports: $Exports<'@blueprintjs/core/lib/cjs/components/button/buttons'>;
}
declare module '@blueprintjs/core/lib/cjs/components/callout/callout.js' {
  declare module.exports: $Exports<'@blueprintjs/core/lib/cjs/components/callout/callout'>;
}
declare module '@blueprintjs/core/lib/cjs/components/card/card.js' {
  declare module.exports: $Exports<'@blueprintjs/core/lib/cjs/components/card/card'>;
}
declare module '@blueprintjs/core/lib/cjs/components/collapse/collapse.js' {
  declare module.exports: $Exports<'@blueprintjs/core/lib/cjs/components/collapse/collapse'>;
}
declare module '@blueprintjs/core/lib/cjs/components/collapsible-list/collapsibleList.js' {
  declare module.exports: $Exports<'@blueprintjs/core/lib/cjs/components/collapsible-list/collapsibleList'>;
}
declare module '@blueprintjs/core/lib/cjs/components/context-menu/contextMenu.js' {
  declare module.exports: $Exports<'@blueprintjs/core/lib/cjs/components/context-menu/contextMenu'>;
}
declare module '@blueprintjs/core/lib/cjs/components/context-menu/contextMenuTarget.js' {
  declare module.exports: $Exports<'@blueprintjs/core/lib/cjs/components/context-menu/contextMenuTarget'>;
}
declare module '@blueprintjs/core/lib/cjs/components/dialog/dialog.js' {
  declare module.exports: $Exports<'@blueprintjs/core/lib/cjs/components/dialog/dialog'>;
}
declare module '@blueprintjs/core/lib/cjs/components/divider/divider.js' {
  declare module.exports: $Exports<'@blueprintjs/core/lib/cjs/components/divider/divider'>;
}
declare module '@blueprintjs/core/lib/cjs/components/drawer/drawer.js' {
  declare module.exports: $Exports<'@blueprintjs/core/lib/cjs/components/drawer/drawer'>;
}
declare module '@blueprintjs/core/lib/cjs/components/editable-text/editableText.js' {
  declare module.exports: $Exports<'@blueprintjs/core/lib/cjs/components/editable-text/editableText'>;
}
declare module '@blueprintjs/core/lib/cjs/components/forms/controlGroup.js' {
  declare module.exports: $Exports<'@blueprintjs/core/lib/cjs/components/forms/controlGroup'>;
}
declare module '@blueprintjs/core/lib/cjs/components/forms/controls.js' {
  declare module.exports: $Exports<'@blueprintjs/core/lib/cjs/components/forms/controls'>;
}
declare module '@blueprintjs/core/lib/cjs/components/forms/fileInput.js' {
  declare module.exports: $Exports<'@blueprintjs/core/lib/cjs/components/forms/fileInput'>;
}
declare module '@blueprintjs/core/lib/cjs/components/forms/formGroup.js' {
  declare module.exports: $Exports<'@blueprintjs/core/lib/cjs/components/forms/formGroup'>;
}
declare module '@blueprintjs/core/lib/cjs/components/forms/inputGroup.js' {
  declare module.exports: $Exports<'@blueprintjs/core/lib/cjs/components/forms/inputGroup'>;
}
declare module '@blueprintjs/core/lib/cjs/components/forms/numericInput.js' {
  declare module.exports: $Exports<'@blueprintjs/core/lib/cjs/components/forms/numericInput'>;
}
declare module '@blueprintjs/core/lib/cjs/components/forms/numericInputUtils.js' {
  declare module.exports: $Exports<'@blueprintjs/core/lib/cjs/components/forms/numericInputUtils'>;
}
declare module '@blueprintjs/core/lib/cjs/components/forms/radioGroup.js' {
  declare module.exports: $Exports<'@blueprintjs/core/lib/cjs/components/forms/radioGroup'>;
}
declare module '@blueprintjs/core/lib/cjs/components/forms/textArea.js' {
  declare module.exports: $Exports<'@blueprintjs/core/lib/cjs/components/forms/textArea'>;
}
declare module '@blueprintjs/core/lib/cjs/components/hotkeys/hotkey.js' {
  declare module.exports: $Exports<'@blueprintjs/core/lib/cjs/components/hotkeys/hotkey'>;
}
declare module '@blueprintjs/core/lib/cjs/components/hotkeys/hotkeyParser.js' {
  declare module.exports: $Exports<'@blueprintjs/core/lib/cjs/components/hotkeys/hotkeyParser'>;
}
declare module '@blueprintjs/core/lib/cjs/components/hotkeys/hotkeys.js' {
  declare module.exports: $Exports<'@blueprintjs/core/lib/cjs/components/hotkeys/hotkeys'>;
}
declare module '@blueprintjs/core/lib/cjs/components/hotkeys/hotkeysDialog.js' {
  declare module.exports: $Exports<'@blueprintjs/core/lib/cjs/components/hotkeys/hotkeysDialog'>;
}
declare module '@blueprintjs/core/lib/cjs/components/hotkeys/hotkeysEvents.js' {
  declare module.exports: $Exports<'@blueprintjs/core/lib/cjs/components/hotkeys/hotkeysEvents'>;
}
declare module '@blueprintjs/core/lib/cjs/components/hotkeys/hotkeysTarget.js' {
  declare module.exports: $Exports<'@blueprintjs/core/lib/cjs/components/hotkeys/hotkeysTarget'>;
}
declare module '@blueprintjs/core/lib/cjs/components/hotkeys/keyCombo.js' {
  declare module.exports: $Exports<'@blueprintjs/core/lib/cjs/components/hotkeys/keyCombo'>;
}
declare module '@blueprintjs/core/lib/cjs/components/html-select/htmlSelect.js' {
  declare module.exports: $Exports<'@blueprintjs/core/lib/cjs/components/html-select/htmlSelect'>;
}
declare module '@blueprintjs/core/lib/cjs/components/html-table/htmlTable.js' {
  declare module.exports: $Exports<'@blueprintjs/core/lib/cjs/components/html-table/htmlTable'>;
}
declare module '@blueprintjs/core/lib/cjs/components/html/html.js' {
  declare module.exports: $Exports<'@blueprintjs/core/lib/cjs/components/html/html'>;
}
declare module '@blueprintjs/core/lib/cjs/components/icon/icon.js' {
  declare module.exports: $Exports<'@blueprintjs/core/lib/cjs/components/icon/icon'>;
}
declare module '@blueprintjs/core/lib/cjs/components/index' {
  declare module.exports: $Exports<'@blueprintjs/core/lib/cjs/components'>;
}
declare module '@blueprintjs/core/lib/cjs/components/index.js' {
  declare module.exports: $Exports<'@blueprintjs/core/lib/cjs/components'>;
}
declare module '@blueprintjs/core/lib/cjs/components/menu/menu.js' {
  declare module.exports: $Exports<'@blueprintjs/core/lib/cjs/components/menu/menu'>;
}
declare module '@blueprintjs/core/lib/cjs/components/menu/menuDivider.js' {
  declare module.exports: $Exports<'@blueprintjs/core/lib/cjs/components/menu/menuDivider'>;
}
declare module '@blueprintjs/core/lib/cjs/components/menu/menuItem.js' {
  declare module.exports: $Exports<'@blueprintjs/core/lib/cjs/components/menu/menuItem'>;
}
declare module '@blueprintjs/core/lib/cjs/components/navbar/navbar.js' {
  declare module.exports: $Exports<'@blueprintjs/core/lib/cjs/components/navbar/navbar'>;
}
declare module '@blueprintjs/core/lib/cjs/components/navbar/navbarDivider.js' {
  declare module.exports: $Exports<'@blueprintjs/core/lib/cjs/components/navbar/navbarDivider'>;
}
declare module '@blueprintjs/core/lib/cjs/components/navbar/navbarGroup.js' {
  declare module.exports: $Exports<'@blueprintjs/core/lib/cjs/components/navbar/navbarGroup'>;
}
declare module '@blueprintjs/core/lib/cjs/components/navbar/navbarHeading.js' {
  declare module.exports: $Exports<'@blueprintjs/core/lib/cjs/components/navbar/navbarHeading'>;
}
declare module '@blueprintjs/core/lib/cjs/components/non-ideal-state/nonIdealState.js' {
  declare module.exports: $Exports<'@blueprintjs/core/lib/cjs/components/non-ideal-state/nonIdealState'>;
}
declare module '@blueprintjs/core/lib/cjs/components/overflow-list/overflowList.js' {
  declare module.exports: $Exports<'@blueprintjs/core/lib/cjs/components/overflow-list/overflowList'>;
}
declare module '@blueprintjs/core/lib/cjs/components/overlay/overlay.js' {
  declare module.exports: $Exports<'@blueprintjs/core/lib/cjs/components/overlay/overlay'>;
}
declare module '@blueprintjs/core/lib/cjs/components/panel-stack/panelProps.js' {
  declare module.exports: $Exports<'@blueprintjs/core/lib/cjs/components/panel-stack/panelProps'>;
}
declare module '@blueprintjs/core/lib/cjs/components/panel-stack/panelStack.js' {
  declare module.exports: $Exports<'@blueprintjs/core/lib/cjs/components/panel-stack/panelStack'>;
}
declare module '@blueprintjs/core/lib/cjs/components/panel-stack/panelView.js' {
  declare module.exports: $Exports<'@blueprintjs/core/lib/cjs/components/panel-stack/panelView'>;
}
declare module '@blueprintjs/core/lib/cjs/components/popover/popover.js' {
  declare module.exports: $Exports<'@blueprintjs/core/lib/cjs/components/popover/popover'>;
}
declare module '@blueprintjs/core/lib/cjs/components/popover/popoverArrow.js' {
  declare module.exports: $Exports<'@blueprintjs/core/lib/cjs/components/popover/popoverArrow'>;
}
declare module '@blueprintjs/core/lib/cjs/components/popover/popoverMigrationUtils.js' {
  declare module.exports: $Exports<'@blueprintjs/core/lib/cjs/components/popover/popoverMigrationUtils'>;
}
declare module '@blueprintjs/core/lib/cjs/components/popover/popoverSharedProps.js' {
  declare module.exports: $Exports<'@blueprintjs/core/lib/cjs/components/popover/popoverSharedProps'>;
}
declare module '@blueprintjs/core/lib/cjs/components/popover/popperUtils.js' {
  declare module.exports: $Exports<'@blueprintjs/core/lib/cjs/components/popover/popperUtils'>;
}
declare module '@blueprintjs/core/lib/cjs/components/portal/portal.js' {
  declare module.exports: $Exports<'@blueprintjs/core/lib/cjs/components/portal/portal'>;
}
declare module '@blueprintjs/core/lib/cjs/components/progress-bar/progressBar.js' {
  declare module.exports: $Exports<'@blueprintjs/core/lib/cjs/components/progress-bar/progressBar'>;
}
declare module '@blueprintjs/core/lib/cjs/components/resize-sensor/resizeSensor.js' {
  declare module.exports: $Exports<'@blueprintjs/core/lib/cjs/components/resize-sensor/resizeSensor'>;
}
declare module '@blueprintjs/core/lib/cjs/components/slider/handle.js' {
  declare module.exports: $Exports<'@blueprintjs/core/lib/cjs/components/slider/handle'>;
}
declare module '@blueprintjs/core/lib/cjs/components/slider/handleProps.js' {
  declare module.exports: $Exports<'@blueprintjs/core/lib/cjs/components/slider/handleProps'>;
}
declare module '@blueprintjs/core/lib/cjs/components/slider/multiSlider.js' {
  declare module.exports: $Exports<'@blueprintjs/core/lib/cjs/components/slider/multiSlider'>;
}
declare module '@blueprintjs/core/lib/cjs/components/slider/rangeSlider.js' {
  declare module.exports: $Exports<'@blueprintjs/core/lib/cjs/components/slider/rangeSlider'>;
}
declare module '@blueprintjs/core/lib/cjs/components/slider/slider.js' {
  declare module.exports: $Exports<'@blueprintjs/core/lib/cjs/components/slider/slider'>;
}
declare module '@blueprintjs/core/lib/cjs/components/slider/sliderUtils.js' {
  declare module.exports: $Exports<'@blueprintjs/core/lib/cjs/components/slider/sliderUtils'>;
}
declare module '@blueprintjs/core/lib/cjs/components/spinner/spinner.js' {
  declare module.exports: $Exports<'@blueprintjs/core/lib/cjs/components/spinner/spinner'>;
}
declare module '@blueprintjs/core/lib/cjs/components/tabs/tab.js' {
  declare module.exports: $Exports<'@blueprintjs/core/lib/cjs/components/tabs/tab'>;
}
declare module '@blueprintjs/core/lib/cjs/components/tabs/tabs.js' {
  declare module.exports: $Exports<'@blueprintjs/core/lib/cjs/components/tabs/tabs'>;
}
declare module '@blueprintjs/core/lib/cjs/components/tabs/tabTitle.js' {
  declare module.exports: $Exports<'@blueprintjs/core/lib/cjs/components/tabs/tabTitle'>;
}
declare module '@blueprintjs/core/lib/cjs/components/tag-input/tagInput.js' {
  declare module.exports: $Exports<'@blueprintjs/core/lib/cjs/components/tag-input/tagInput'>;
}
declare module '@blueprintjs/core/lib/cjs/components/tag/tag.js' {
  declare module.exports: $Exports<'@blueprintjs/core/lib/cjs/components/tag/tag'>;
}
declare module '@blueprintjs/core/lib/cjs/components/text/text.js' {
  declare module.exports: $Exports<'@blueprintjs/core/lib/cjs/components/text/text'>;
}
declare module '@blueprintjs/core/lib/cjs/components/toast/toast.js' {
  declare module.exports: $Exports<'@blueprintjs/core/lib/cjs/components/toast/toast'>;
}
declare module '@blueprintjs/core/lib/cjs/components/toast/toaster.js' {
  declare module.exports: $Exports<'@blueprintjs/core/lib/cjs/components/toast/toaster'>;
}
declare module '@blueprintjs/core/lib/cjs/components/tooltip/tooltip.js' {
  declare module.exports: $Exports<'@blueprintjs/core/lib/cjs/components/tooltip/tooltip'>;
}
declare module '@blueprintjs/core/lib/cjs/components/tree/tree.js' {
  declare module.exports: $Exports<'@blueprintjs/core/lib/cjs/components/tree/tree'>;
}
declare module '@blueprintjs/core/lib/cjs/components/tree/treeNode.js' {
  declare module.exports: $Exports<'@blueprintjs/core/lib/cjs/components/tree/treeNode'>;
}
declare module '@blueprintjs/core/lib/cjs/index' {
  declare module.exports: $Exports<'@blueprintjs/core/lib/cjs'>;
}
declare module '@blueprintjs/core/lib/cjs/index.js' {
  declare module.exports: $Exports<'@blueprintjs/core/lib/cjs'>;
}
declare module '@blueprintjs/core/lib/esm/accessibility/focusStyleManager.js' {
  declare module.exports: $Exports<'@blueprintjs/core/lib/esm/accessibility/focusStyleManager'>;
}
declare module '@blueprintjs/core/lib/esm/accessibility/index' {
  declare module.exports: $Exports<'@blueprintjs/core/lib/esm/accessibility'>;
}
declare module '@blueprintjs/core/lib/esm/accessibility/index.js' {
  declare module.exports: $Exports<'@blueprintjs/core/lib/esm/accessibility'>;
}
declare module '@blueprintjs/core/lib/esm/common/abstractComponent.js' {
  declare module.exports: $Exports<'@blueprintjs/core/lib/esm/common/abstractComponent'>;
}
declare module '@blueprintjs/core/lib/esm/common/abstractComponent2.js' {
  declare module.exports: $Exports<'@blueprintjs/core/lib/esm/common/abstractComponent2'>;
}
declare module '@blueprintjs/core/lib/esm/common/abstractPureComponent.js' {
  declare module.exports: $Exports<'@blueprintjs/core/lib/esm/common/abstractPureComponent'>;
}
declare module '@blueprintjs/core/lib/esm/common/abstractPureComponent2.js' {
  declare module.exports: $Exports<'@blueprintjs/core/lib/esm/common/abstractPureComponent2'>;
}
declare module '@blueprintjs/core/lib/esm/common/alignment.js' {
  declare module.exports: $Exports<'@blueprintjs/core/lib/esm/common/alignment'>;
}
declare module '@blueprintjs/core/lib/esm/common/boundary.js' {
  declare module.exports: $Exports<'@blueprintjs/core/lib/esm/common/boundary'>;
}
declare module '@blueprintjs/core/lib/esm/common/classes.js' {
  declare module.exports: $Exports<'@blueprintjs/core/lib/esm/common/classes'>;
}
declare module '@blueprintjs/core/lib/esm/common/colors.js' {
  declare module.exports: $Exports<'@blueprintjs/core/lib/esm/common/colors'>;
}
declare module '@blueprintjs/core/lib/esm/common/configureDom4.js' {
  declare module.exports: $Exports<'@blueprintjs/core/lib/esm/common/configureDom4'>;
}
declare module '@blueprintjs/core/lib/esm/common/constructor.js' {
  declare module.exports: $Exports<'@blueprintjs/core/lib/esm/common/constructor'>;
}
declare module '@blueprintjs/core/lib/esm/common/elevation.js' {
  declare module.exports: $Exports<'@blueprintjs/core/lib/esm/common/elevation'>;
}
declare module '@blueprintjs/core/lib/esm/common/errors.js' {
  declare module.exports: $Exports<'@blueprintjs/core/lib/esm/common/errors'>;
}
declare module '@blueprintjs/core/lib/esm/common/index' {
  declare module.exports: $Exports<'@blueprintjs/core/lib/esm/common'>;
}
declare module '@blueprintjs/core/lib/esm/common/index.js' {
  declare module.exports: $Exports<'@blueprintjs/core/lib/esm/common'>;
}
declare module '@blueprintjs/core/lib/esm/common/intent.js' {
  declare module.exports: $Exports<'@blueprintjs/core/lib/esm/common/intent'>;
}
declare module '@blueprintjs/core/lib/esm/common/interactionMode.js' {
  declare module.exports: $Exports<'@blueprintjs/core/lib/esm/common/interactionMode'>;
}
declare module '@blueprintjs/core/lib/esm/common/keys.js' {
  declare module.exports: $Exports<'@blueprintjs/core/lib/esm/common/keys'>;
}
declare module '@blueprintjs/core/lib/esm/common/position.js' {
  declare module.exports: $Exports<'@blueprintjs/core/lib/esm/common/position'>;
}
declare module '@blueprintjs/core/lib/esm/common/props.js' {
  declare module.exports: $Exports<'@blueprintjs/core/lib/esm/common/props'>;
}
declare module '@blueprintjs/core/lib/esm/common/utils.js' {
  declare module.exports: $Exports<'@blueprintjs/core/lib/esm/common/utils'>;
}
declare module '@blueprintjs/core/lib/esm/common/utils/compareUtils.js' {
  declare module.exports: $Exports<'@blueprintjs/core/lib/esm/common/utils/compareUtils'>;
}
declare module '@blueprintjs/core/lib/esm/common/utils/isDarkTheme.js' {
  declare module.exports: $Exports<'@blueprintjs/core/lib/esm/common/utils/isDarkTheme'>;
}
declare module '@blueprintjs/core/lib/esm/common/utils/safeInvokeMember.js' {
  declare module.exports: $Exports<'@blueprintjs/core/lib/esm/common/utils/safeInvokeMember'>;
}
declare module '@blueprintjs/core/lib/esm/compatibility/browser.js' {
  declare module.exports: $Exports<'@blueprintjs/core/lib/esm/compatibility/browser'>;
}
declare module '@blueprintjs/core/lib/esm/compatibility/index' {
  declare module.exports: $Exports<'@blueprintjs/core/lib/esm/compatibility'>;
}
declare module '@blueprintjs/core/lib/esm/compatibility/index.js' {
  declare module.exports: $Exports<'@blueprintjs/core/lib/esm/compatibility'>;
}
declare module '@blueprintjs/core/lib/esm/components/alert/alert.js' {
  declare module.exports: $Exports<'@blueprintjs/core/lib/esm/components/alert/alert'>;
}
declare module '@blueprintjs/core/lib/esm/components/breadcrumbs/breadcrumb.js' {
  declare module.exports: $Exports<'@blueprintjs/core/lib/esm/components/breadcrumbs/breadcrumb'>;
}
declare module '@blueprintjs/core/lib/esm/components/breadcrumbs/breadcrumbs.js' {
  declare module.exports: $Exports<'@blueprintjs/core/lib/esm/components/breadcrumbs/breadcrumbs'>;
}
declare module '@blueprintjs/core/lib/esm/components/button/abstractButton.js' {
  declare module.exports: $Exports<'@blueprintjs/core/lib/esm/components/button/abstractButton'>;
}
declare module '@blueprintjs/core/lib/esm/components/button/buttonGroup.js' {
  declare module.exports: $Exports<'@blueprintjs/core/lib/esm/components/button/buttonGroup'>;
}
declare module '@blueprintjs/core/lib/esm/components/button/buttons.js' {
  declare module.exports: $Exports<'@blueprintjs/core/lib/esm/components/button/buttons'>;
}
declare module '@blueprintjs/core/lib/esm/components/callout/callout.js' {
  declare module.exports: $Exports<'@blueprintjs/core/lib/esm/components/callout/callout'>;
}
declare module '@blueprintjs/core/lib/esm/components/card/card.js' {
  declare module.exports: $Exports<'@blueprintjs/core/lib/esm/components/card/card'>;
}
declare module '@blueprintjs/core/lib/esm/components/collapse/collapse.js' {
  declare module.exports: $Exports<'@blueprintjs/core/lib/esm/components/collapse/collapse'>;
}
declare module '@blueprintjs/core/lib/esm/components/collapsible-list/collapsibleList.js' {
  declare module.exports: $Exports<'@blueprintjs/core/lib/esm/components/collapsible-list/collapsibleList'>;
}
declare module '@blueprintjs/core/lib/esm/components/context-menu/contextMenu.js' {
  declare module.exports: $Exports<'@blueprintjs/core/lib/esm/components/context-menu/contextMenu'>;
}
declare module '@blueprintjs/core/lib/esm/components/context-menu/contextMenuTarget.js' {
  declare module.exports: $Exports<'@blueprintjs/core/lib/esm/components/context-menu/contextMenuTarget'>;
}
declare module '@blueprintjs/core/lib/esm/components/dialog/dialog.js' {
  declare module.exports: $Exports<'@blueprintjs/core/lib/esm/components/dialog/dialog'>;
}
declare module '@blueprintjs/core/lib/esm/components/divider/divider.js' {
  declare module.exports: $Exports<'@blueprintjs/core/lib/esm/components/divider/divider'>;
}
declare module '@blueprintjs/core/lib/esm/components/drawer/drawer.js' {
  declare module.exports: $Exports<'@blueprintjs/core/lib/esm/components/drawer/drawer'>;
}
declare module '@blueprintjs/core/lib/esm/components/editable-text/editableText.js' {
  declare module.exports: $Exports<'@blueprintjs/core/lib/esm/components/editable-text/editableText'>;
}
declare module '@blueprintjs/core/lib/esm/components/forms/controlGroup.js' {
  declare module.exports: $Exports<'@blueprintjs/core/lib/esm/components/forms/controlGroup'>;
}
declare module '@blueprintjs/core/lib/esm/components/forms/controls.js' {
  declare module.exports: $Exports<'@blueprintjs/core/lib/esm/components/forms/controls'>;
}
declare module '@blueprintjs/core/lib/esm/components/forms/fileInput.js' {
  declare module.exports: $Exports<'@blueprintjs/core/lib/esm/components/forms/fileInput'>;
}
declare module '@blueprintjs/core/lib/esm/components/forms/formGroup.js' {
  declare module.exports: $Exports<'@blueprintjs/core/lib/esm/components/forms/formGroup'>;
}
declare module '@blueprintjs/core/lib/esm/components/forms/inputGroup.js' {
  declare module.exports: $Exports<'@blueprintjs/core/lib/esm/components/forms/inputGroup'>;
}
declare module '@blueprintjs/core/lib/esm/components/forms/numericInput.js' {
  declare module.exports: $Exports<'@blueprintjs/core/lib/esm/components/forms/numericInput'>;
}
declare module '@blueprintjs/core/lib/esm/components/forms/numericInputUtils.js' {
  declare module.exports: $Exports<'@blueprintjs/core/lib/esm/components/forms/numericInputUtils'>;
}
declare module '@blueprintjs/core/lib/esm/components/forms/radioGroup.js' {
  declare module.exports: $Exports<'@blueprintjs/core/lib/esm/components/forms/radioGroup'>;
}
declare module '@blueprintjs/core/lib/esm/components/forms/textArea.js' {
  declare module.exports: $Exports<'@blueprintjs/core/lib/esm/components/forms/textArea'>;
}
declare module '@blueprintjs/core/lib/esm/components/hotkeys/hotkey.js' {
  declare module.exports: $Exports<'@blueprintjs/core/lib/esm/components/hotkeys/hotkey'>;
}
declare module '@blueprintjs/core/lib/esm/components/hotkeys/hotkeyParser.js' {
  declare module.exports: $Exports<'@blueprintjs/core/lib/esm/components/hotkeys/hotkeyParser'>;
}
declare module '@blueprintjs/core/lib/esm/components/hotkeys/hotkeys.js' {
  declare module.exports: $Exports<'@blueprintjs/core/lib/esm/components/hotkeys/hotkeys'>;
}
declare module '@blueprintjs/core/lib/esm/components/hotkeys/hotkeysDialog.js' {
  declare module.exports: $Exports<'@blueprintjs/core/lib/esm/components/hotkeys/hotkeysDialog'>;
}
declare module '@blueprintjs/core/lib/esm/components/hotkeys/hotkeysEvents.js' {
  declare module.exports: $Exports<'@blueprintjs/core/lib/esm/components/hotkeys/hotkeysEvents'>;
}
declare module '@blueprintjs/core/lib/esm/components/hotkeys/hotkeysTarget.js' {
  declare module.exports: $Exports<'@blueprintjs/core/lib/esm/components/hotkeys/hotkeysTarget'>;
}
declare module '@blueprintjs/core/lib/esm/components/hotkeys/keyCombo.js' {
  declare module.exports: $Exports<'@blueprintjs/core/lib/esm/components/hotkeys/keyCombo'>;
}
declare module '@blueprintjs/core/lib/esm/components/html-select/htmlSelect.js' {
  declare module.exports: $Exports<'@blueprintjs/core/lib/esm/components/html-select/htmlSelect'>;
}
declare module '@blueprintjs/core/lib/esm/components/html-table/htmlTable.js' {
  declare module.exports: $Exports<'@blueprintjs/core/lib/esm/components/html-table/htmlTable'>;
}
declare module '@blueprintjs/core/lib/esm/components/html/html.js' {
  declare module.exports: $Exports<'@blueprintjs/core/lib/esm/components/html/html'>;
}
declare module '@blueprintjs/core/lib/esm/components/icon/icon.js' {
  declare module.exports: $Exports<'@blueprintjs/core/lib/esm/components/icon/icon'>;
}
declare module '@blueprintjs/core/lib/esm/components/index' {
  declare module.exports: $Exports<'@blueprintjs/core/lib/esm/components'>;
}
declare module '@blueprintjs/core/lib/esm/components/index.js' {
  declare module.exports: $Exports<'@blueprintjs/core/lib/esm/components'>;
}
declare module '@blueprintjs/core/lib/esm/components/menu/menu.js' {
  declare module.exports: $Exports<'@blueprintjs/core/lib/esm/components/menu/menu'>;
}
declare module '@blueprintjs/core/lib/esm/components/menu/menuDivider.js' {
  declare module.exports: $Exports<'@blueprintjs/core/lib/esm/components/menu/menuDivider'>;
}
declare module '@blueprintjs/core/lib/esm/components/menu/menuItem.js' {
  declare module.exports: $Exports<'@blueprintjs/core/lib/esm/components/menu/menuItem'>;
}
declare module '@blueprintjs/core/lib/esm/components/navbar/navbar.js' {
  declare module.exports: $Exports<'@blueprintjs/core/lib/esm/components/navbar/navbar'>;
}
declare module '@blueprintjs/core/lib/esm/components/navbar/navbarDivider.js' {
  declare module.exports: $Exports<'@blueprintjs/core/lib/esm/components/navbar/navbarDivider'>;
}
declare module '@blueprintjs/core/lib/esm/components/navbar/navbarGroup.js' {
  declare module.exports: $Exports<'@blueprintjs/core/lib/esm/components/navbar/navbarGroup'>;
}
declare module '@blueprintjs/core/lib/esm/components/navbar/navbarHeading.js' {
  declare module.exports: $Exports<'@blueprintjs/core/lib/esm/components/navbar/navbarHeading'>;
}
declare module '@blueprintjs/core/lib/esm/components/non-ideal-state/nonIdealState.js' {
  declare module.exports: $Exports<'@blueprintjs/core/lib/esm/components/non-ideal-state/nonIdealState'>;
}
declare module '@blueprintjs/core/lib/esm/components/overflow-list/overflowList.js' {
  declare module.exports: $Exports<'@blueprintjs/core/lib/esm/components/overflow-list/overflowList'>;
}
declare module '@blueprintjs/core/lib/esm/components/overlay/overlay.js' {
  declare module.exports: $Exports<'@blueprintjs/core/lib/esm/components/overlay/overlay'>;
}
declare module '@blueprintjs/core/lib/esm/components/panel-stack/panelProps.js' {
  declare module.exports: $Exports<'@blueprintjs/core/lib/esm/components/panel-stack/panelProps'>;
}
declare module '@blueprintjs/core/lib/esm/components/panel-stack/panelStack.js' {
  declare module.exports: $Exports<'@blueprintjs/core/lib/esm/components/panel-stack/panelStack'>;
}
declare module '@blueprintjs/core/lib/esm/components/panel-stack/panelView.js' {
  declare module.exports: $Exports<'@blueprintjs/core/lib/esm/components/panel-stack/panelView'>;
}
declare module '@blueprintjs/core/lib/esm/components/popover/popover.js' {
  declare module.exports: $Exports<'@blueprintjs/core/lib/esm/components/popover/popover'>;
}
declare module '@blueprintjs/core/lib/esm/components/popover/popoverArrow.js' {
  declare module.exports: $Exports<'@blueprintjs/core/lib/esm/components/popover/popoverArrow'>;
}
declare module '@blueprintjs/core/lib/esm/components/popover/popoverMigrationUtils.js' {
  declare module.exports: $Exports<'@blueprintjs/core/lib/esm/components/popover/popoverMigrationUtils'>;
}
declare module '@blueprintjs/core/lib/esm/components/popover/popoverSharedProps.js' {
  declare module.exports: $Exports<'@blueprintjs/core/lib/esm/components/popover/popoverSharedProps'>;
}
declare module '@blueprintjs/core/lib/esm/components/popover/popperUtils.js' {
  declare module.exports: $Exports<'@blueprintjs/core/lib/esm/components/popover/popperUtils'>;
}
declare module '@blueprintjs/core/lib/esm/components/portal/portal.js' {
  declare module.exports: $Exports<'@blueprintjs/core/lib/esm/components/portal/portal'>;
}
declare module '@blueprintjs/core/lib/esm/components/progress-bar/progressBar.js' {
  declare module.exports: $Exports<'@blueprintjs/core/lib/esm/components/progress-bar/progressBar'>;
}
declare module '@blueprintjs/core/lib/esm/components/resize-sensor/resizeSensor.js' {
  declare module.exports: $Exports<'@blueprintjs/core/lib/esm/components/resize-sensor/resizeSensor'>;
}
declare module '@blueprintjs/core/lib/esm/components/slider/handle.js' {
  declare module.exports: $Exports<'@blueprintjs/core/lib/esm/components/slider/handle'>;
}
declare module '@blueprintjs/core/lib/esm/components/slider/handleProps.js' {
  declare module.exports: $Exports<'@blueprintjs/core/lib/esm/components/slider/handleProps'>;
}
declare module '@blueprintjs/core/lib/esm/components/slider/multiSlider.js' {
  declare module.exports: $Exports<'@blueprintjs/core/lib/esm/components/slider/multiSlider'>;
}
declare module '@blueprintjs/core/lib/esm/components/slider/rangeSlider.js' {
  declare module.exports: $Exports<'@blueprintjs/core/lib/esm/components/slider/rangeSlider'>;
}
declare module '@blueprintjs/core/lib/esm/components/slider/slider.js' {
  declare module.exports: $Exports<'@blueprintjs/core/lib/esm/components/slider/slider'>;
}
declare module '@blueprintjs/core/lib/esm/components/slider/sliderUtils.js' {
  declare module.exports: $Exports<'@blueprintjs/core/lib/esm/components/slider/sliderUtils'>;
}
declare module '@blueprintjs/core/lib/esm/components/spinner/spinner.js' {
  declare module.exports: $Exports<'@blueprintjs/core/lib/esm/components/spinner/spinner'>;
}
declare module '@blueprintjs/core/lib/esm/components/tabs/tab.js' {
  declare module.exports: $Exports<'@blueprintjs/core/lib/esm/components/tabs/tab'>;
}
declare module '@blueprintjs/core/lib/esm/components/tabs/tabs.js' {
  declare module.exports: $Exports<'@blueprintjs/core/lib/esm/components/tabs/tabs'>;
}
declare module '@blueprintjs/core/lib/esm/components/tabs/tabTitle.js' {
  declare module.exports: $Exports<'@blueprintjs/core/lib/esm/components/tabs/tabTitle'>;
}
declare module '@blueprintjs/core/lib/esm/components/tag-input/tagInput.js' {
  declare module.exports: $Exports<'@blueprintjs/core/lib/esm/components/tag-input/tagInput'>;
}
declare module '@blueprintjs/core/lib/esm/components/tag/tag.js' {
  declare module.exports: $Exports<'@blueprintjs/core/lib/esm/components/tag/tag'>;
}
declare module '@blueprintjs/core/lib/esm/components/text/text.js' {
  declare module.exports: $Exports<'@blueprintjs/core/lib/esm/components/text/text'>;
}
declare module '@blueprintjs/core/lib/esm/components/toast/toast.js' {
  declare module.exports: $Exports<'@blueprintjs/core/lib/esm/components/toast/toast'>;
}
declare module '@blueprintjs/core/lib/esm/components/toast/toaster.js' {
  declare module.exports: $Exports<'@blueprintjs/core/lib/esm/components/toast/toaster'>;
}
declare module '@blueprintjs/core/lib/esm/components/tooltip/tooltip.js' {
  declare module.exports: $Exports<'@blueprintjs/core/lib/esm/components/tooltip/tooltip'>;
}
declare module '@blueprintjs/core/lib/esm/components/tree/tree.js' {
  declare module.exports: $Exports<'@blueprintjs/core/lib/esm/components/tree/tree'>;
}
declare module '@blueprintjs/core/lib/esm/components/tree/treeNode.js' {
  declare module.exports: $Exports<'@blueprintjs/core/lib/esm/components/tree/treeNode'>;
}
declare module '@blueprintjs/core/lib/esm/index' {
  declare module.exports: $Exports<'@blueprintjs/core/lib/esm'>;
}
declare module '@blueprintjs/core/lib/esm/index.js' {
  declare module.exports: $Exports<'@blueprintjs/core/lib/esm'>;
}
declare module '@blueprintjs/core/lib/esnext/accessibility/focusStyleManager.js' {
  declare module.exports: $Exports<'@blueprintjs/core/lib/esnext/accessibility/focusStyleManager'>;
}
declare module '@blueprintjs/core/lib/esnext/accessibility/index' {
  declare module.exports: $Exports<'@blueprintjs/core/lib/esnext/accessibility'>;
}
declare module '@blueprintjs/core/lib/esnext/accessibility/index.js' {
  declare module.exports: $Exports<'@blueprintjs/core/lib/esnext/accessibility'>;
}
declare module '@blueprintjs/core/lib/esnext/common/abstractComponent.js' {
  declare module.exports: $Exports<'@blueprintjs/core/lib/esnext/common/abstractComponent'>;
}
declare module '@blueprintjs/core/lib/esnext/common/abstractComponent2.js' {
  declare module.exports: $Exports<'@blueprintjs/core/lib/esnext/common/abstractComponent2'>;
}
declare module '@blueprintjs/core/lib/esnext/common/abstractPureComponent.js' {
  declare module.exports: $Exports<'@blueprintjs/core/lib/esnext/common/abstractPureComponent'>;
}
declare module '@blueprintjs/core/lib/esnext/common/abstractPureComponent2.js' {
  declare module.exports: $Exports<'@blueprintjs/core/lib/esnext/common/abstractPureComponent2'>;
}
declare module '@blueprintjs/core/lib/esnext/common/alignment.js' {
  declare module.exports: $Exports<'@blueprintjs/core/lib/esnext/common/alignment'>;
}
declare module '@blueprintjs/core/lib/esnext/common/boundary.js' {
  declare module.exports: $Exports<'@blueprintjs/core/lib/esnext/common/boundary'>;
}
declare module '@blueprintjs/core/lib/esnext/common/classes.js' {
  declare module.exports: $Exports<'@blueprintjs/core/lib/esnext/common/classes'>;
}
declare module '@blueprintjs/core/lib/esnext/common/colors.js' {
  declare module.exports: $Exports<'@blueprintjs/core/lib/esnext/common/colors'>;
}
declare module '@blueprintjs/core/lib/esnext/common/configureDom4.js' {
  declare module.exports: $Exports<'@blueprintjs/core/lib/esnext/common/configureDom4'>;
}
declare module '@blueprintjs/core/lib/esnext/common/constructor.js' {
  declare module.exports: $Exports<'@blueprintjs/core/lib/esnext/common/constructor'>;
}
declare module '@blueprintjs/core/lib/esnext/common/elevation.js' {
  declare module.exports: $Exports<'@blueprintjs/core/lib/esnext/common/elevation'>;
}
declare module '@blueprintjs/core/lib/esnext/common/errors.js' {
  declare module.exports: $Exports<'@blueprintjs/core/lib/esnext/common/errors'>;
}
declare module '@blueprintjs/core/lib/esnext/common/index' {
  declare module.exports: $Exports<'@blueprintjs/core/lib/esnext/common'>;
}
declare module '@blueprintjs/core/lib/esnext/common/index.js' {
  declare module.exports: $Exports<'@blueprintjs/core/lib/esnext/common'>;
}
declare module '@blueprintjs/core/lib/esnext/common/intent.js' {
  declare module.exports: $Exports<'@blueprintjs/core/lib/esnext/common/intent'>;
}
declare module '@blueprintjs/core/lib/esnext/common/interactionMode.js' {
  declare module.exports: $Exports<'@blueprintjs/core/lib/esnext/common/interactionMode'>;
}
declare module '@blueprintjs/core/lib/esnext/common/keys.js' {
  declare module.exports: $Exports<'@blueprintjs/core/lib/esnext/common/keys'>;
}
declare module '@blueprintjs/core/lib/esnext/common/position.js' {
  declare module.exports: $Exports<'@blueprintjs/core/lib/esnext/common/position'>;
}
declare module '@blueprintjs/core/lib/esnext/common/props.js' {
  declare module.exports: $Exports<'@blueprintjs/core/lib/esnext/common/props'>;
}
declare module '@blueprintjs/core/lib/esnext/common/utils.js' {
  declare module.exports: $Exports<'@blueprintjs/core/lib/esnext/common/utils'>;
}
declare module '@blueprintjs/core/lib/esnext/common/utils/compareUtils.js' {
  declare module.exports: $Exports<'@blueprintjs/core/lib/esnext/common/utils/compareUtils'>;
}
declare module '@blueprintjs/core/lib/esnext/common/utils/isDarkTheme.js' {
  declare module.exports: $Exports<'@blueprintjs/core/lib/esnext/common/utils/isDarkTheme'>;
}
declare module '@blueprintjs/core/lib/esnext/common/utils/safeInvokeMember.js' {
  declare module.exports: $Exports<'@blueprintjs/core/lib/esnext/common/utils/safeInvokeMember'>;
}
declare module '@blueprintjs/core/lib/esnext/compatibility/browser.js' {
  declare module.exports: $Exports<'@blueprintjs/core/lib/esnext/compatibility/browser'>;
}
declare module '@blueprintjs/core/lib/esnext/compatibility/index' {
  declare module.exports: $Exports<'@blueprintjs/core/lib/esnext/compatibility'>;
}
declare module '@blueprintjs/core/lib/esnext/compatibility/index.js' {
  declare module.exports: $Exports<'@blueprintjs/core/lib/esnext/compatibility'>;
}
declare module '@blueprintjs/core/lib/esnext/components/alert/alert.js' {
  declare module.exports: $Exports<'@blueprintjs/core/lib/esnext/components/alert/alert'>;
}
declare module '@blueprintjs/core/lib/esnext/components/breadcrumbs/breadcrumb.js' {
  declare module.exports: $Exports<'@blueprintjs/core/lib/esnext/components/breadcrumbs/breadcrumb'>;
}
declare module '@blueprintjs/core/lib/esnext/components/breadcrumbs/breadcrumbs.js' {
  declare module.exports: $Exports<'@blueprintjs/core/lib/esnext/components/breadcrumbs/breadcrumbs'>;
}
declare module '@blueprintjs/core/lib/esnext/components/button/abstractButton.js' {
  declare module.exports: $Exports<'@blueprintjs/core/lib/esnext/components/button/abstractButton'>;
}
declare module '@blueprintjs/core/lib/esnext/components/button/buttonGroup.js' {
  declare module.exports: $Exports<'@blueprintjs/core/lib/esnext/components/button/buttonGroup'>;
}
declare module '@blueprintjs/core/lib/esnext/components/button/buttons.js' {
  declare module.exports: $Exports<'@blueprintjs/core/lib/esnext/components/button/buttons'>;
}
declare module '@blueprintjs/core/lib/esnext/components/callout/callout.js' {
  declare module.exports: $Exports<'@blueprintjs/core/lib/esnext/components/callout/callout'>;
}
declare module '@blueprintjs/core/lib/esnext/components/card/card.js' {
  declare module.exports: $Exports<'@blueprintjs/core/lib/esnext/components/card/card'>;
}
declare module '@blueprintjs/core/lib/esnext/components/collapse/collapse.js' {
  declare module.exports: $Exports<'@blueprintjs/core/lib/esnext/components/collapse/collapse'>;
}
declare module '@blueprintjs/core/lib/esnext/components/collapsible-list/collapsibleList.js' {
  declare module.exports: $Exports<'@blueprintjs/core/lib/esnext/components/collapsible-list/collapsibleList'>;
}
declare module '@blueprintjs/core/lib/esnext/components/context-menu/contextMenu.js' {
  declare module.exports: $Exports<'@blueprintjs/core/lib/esnext/components/context-menu/contextMenu'>;
}
declare module '@blueprintjs/core/lib/esnext/components/context-menu/contextMenuTarget.js' {
  declare module.exports: $Exports<'@blueprintjs/core/lib/esnext/components/context-menu/contextMenuTarget'>;
}
declare module '@blueprintjs/core/lib/esnext/components/dialog/dialog.js' {
  declare module.exports: $Exports<'@blueprintjs/core/lib/esnext/components/dialog/dialog'>;
}
declare module '@blueprintjs/core/lib/esnext/components/divider/divider.js' {
  declare module.exports: $Exports<'@blueprintjs/core/lib/esnext/components/divider/divider'>;
}
declare module '@blueprintjs/core/lib/esnext/components/drawer/drawer.js' {
  declare module.exports: $Exports<'@blueprintjs/core/lib/esnext/components/drawer/drawer'>;
}
declare module '@blueprintjs/core/lib/esnext/components/editable-text/editableText.js' {
  declare module.exports: $Exports<'@blueprintjs/core/lib/esnext/components/editable-text/editableText'>;
}
declare module '@blueprintjs/core/lib/esnext/components/forms/controlGroup.js' {
  declare module.exports: $Exports<'@blueprintjs/core/lib/esnext/components/forms/controlGroup'>;
}
declare module '@blueprintjs/core/lib/esnext/components/forms/controls.js' {
  declare module.exports: $Exports<'@blueprintjs/core/lib/esnext/components/forms/controls'>;
}
declare module '@blueprintjs/core/lib/esnext/components/forms/fileInput.js' {
  declare module.exports: $Exports<'@blueprintjs/core/lib/esnext/components/forms/fileInput'>;
}
declare module '@blueprintjs/core/lib/esnext/components/forms/formGroup.js' {
  declare module.exports: $Exports<'@blueprintjs/core/lib/esnext/components/forms/formGroup'>;
}
declare module '@blueprintjs/core/lib/esnext/components/forms/inputGroup.js' {
  declare module.exports: $Exports<'@blueprintjs/core/lib/esnext/components/forms/inputGroup'>;
}
declare module '@blueprintjs/core/lib/esnext/components/forms/numericInput.js' {
  declare module.exports: $Exports<'@blueprintjs/core/lib/esnext/components/forms/numericInput'>;
}
declare module '@blueprintjs/core/lib/esnext/components/forms/numericInputUtils.js' {
  declare module.exports: $Exports<'@blueprintjs/core/lib/esnext/components/forms/numericInputUtils'>;
}
declare module '@blueprintjs/core/lib/esnext/components/forms/radioGroup.js' {
  declare module.exports: $Exports<'@blueprintjs/core/lib/esnext/components/forms/radioGroup'>;
}
declare module '@blueprintjs/core/lib/esnext/components/forms/textArea.js' {
  declare module.exports: $Exports<'@blueprintjs/core/lib/esnext/components/forms/textArea'>;
}
declare module '@blueprintjs/core/lib/esnext/components/hotkeys/hotkey.js' {
  declare module.exports: $Exports<'@blueprintjs/core/lib/esnext/components/hotkeys/hotkey'>;
}
declare module '@blueprintjs/core/lib/esnext/components/hotkeys/hotkeyParser.js' {
  declare module.exports: $Exports<'@blueprintjs/core/lib/esnext/components/hotkeys/hotkeyParser'>;
}
declare module '@blueprintjs/core/lib/esnext/components/hotkeys/hotkeys.js' {
  declare module.exports: $Exports<'@blueprintjs/core/lib/esnext/components/hotkeys/hotkeys'>;
}
declare module '@blueprintjs/core/lib/esnext/components/hotkeys/hotkeysDialog.js' {
  declare module.exports: $Exports<'@blueprintjs/core/lib/esnext/components/hotkeys/hotkeysDialog'>;
}
declare module '@blueprintjs/core/lib/esnext/components/hotkeys/hotkeysEvents.js' {
  declare module.exports: $Exports<'@blueprintjs/core/lib/esnext/components/hotkeys/hotkeysEvents'>;
}
declare module '@blueprintjs/core/lib/esnext/components/hotkeys/hotkeysTarget.js' {
  declare module.exports: $Exports<'@blueprintjs/core/lib/esnext/components/hotkeys/hotkeysTarget'>;
}
declare module '@blueprintjs/core/lib/esnext/components/hotkeys/keyCombo.js' {
  declare module.exports: $Exports<'@blueprintjs/core/lib/esnext/components/hotkeys/keyCombo'>;
}
declare module '@blueprintjs/core/lib/esnext/components/html-select/htmlSelect.js' {
  declare module.exports: $Exports<'@blueprintjs/core/lib/esnext/components/html-select/htmlSelect'>;
}
declare module '@blueprintjs/core/lib/esnext/components/html-table/htmlTable.js' {
  declare module.exports: $Exports<'@blueprintjs/core/lib/esnext/components/html-table/htmlTable'>;
}
declare module '@blueprintjs/core/lib/esnext/components/html/html.js' {
  declare module.exports: $Exports<'@blueprintjs/core/lib/esnext/components/html/html'>;
}
declare module '@blueprintjs/core/lib/esnext/components/icon/icon.js' {
  declare module.exports: $Exports<'@blueprintjs/core/lib/esnext/components/icon/icon'>;
}
declare module '@blueprintjs/core/lib/esnext/components/index' {
  declare module.exports: $Exports<'@blueprintjs/core/lib/esnext/components'>;
}
declare module '@blueprintjs/core/lib/esnext/components/index.js' {
  declare module.exports: $Exports<'@blueprintjs/core/lib/esnext/components'>;
}
declare module '@blueprintjs/core/lib/esnext/components/menu/menu.js' {
  declare module.exports: $Exports<'@blueprintjs/core/lib/esnext/components/menu/menu'>;
}
declare module '@blueprintjs/core/lib/esnext/components/menu/menuDivider.js' {
  declare module.exports: $Exports<'@blueprintjs/core/lib/esnext/components/menu/menuDivider'>;
}
declare module '@blueprintjs/core/lib/esnext/components/menu/menuItem.js' {
  declare module.exports: $Exports<'@blueprintjs/core/lib/esnext/components/menu/menuItem'>;
}
declare module '@blueprintjs/core/lib/esnext/components/navbar/navbar.js' {
  declare module.exports: $Exports<'@blueprintjs/core/lib/esnext/components/navbar/navbar'>;
}
declare module '@blueprintjs/core/lib/esnext/components/navbar/navbarDivider.js' {
  declare module.exports: $Exports<'@blueprintjs/core/lib/esnext/components/navbar/navbarDivider'>;
}
declare module '@blueprintjs/core/lib/esnext/components/navbar/navbarGroup.js' {
  declare module.exports: $Exports<'@blueprintjs/core/lib/esnext/components/navbar/navbarGroup'>;
}
declare module '@blueprintjs/core/lib/esnext/components/navbar/navbarHeading.js' {
  declare module.exports: $Exports<'@blueprintjs/core/lib/esnext/components/navbar/navbarHeading'>;
}
declare module '@blueprintjs/core/lib/esnext/components/non-ideal-state/nonIdealState.js' {
  declare module.exports: $Exports<'@blueprintjs/core/lib/esnext/components/non-ideal-state/nonIdealState'>;
}
declare module '@blueprintjs/core/lib/esnext/components/overflow-list/overflowList.js' {
  declare module.exports: $Exports<'@blueprintjs/core/lib/esnext/components/overflow-list/overflowList'>;
}
declare module '@blueprintjs/core/lib/esnext/components/overlay/overlay.js' {
  declare module.exports: $Exports<'@blueprintjs/core/lib/esnext/components/overlay/overlay'>;
}
declare module '@blueprintjs/core/lib/esnext/components/panel-stack/panelProps.js' {
  declare module.exports: $Exports<'@blueprintjs/core/lib/esnext/components/panel-stack/panelProps'>;
}
declare module '@blueprintjs/core/lib/esnext/components/panel-stack/panelStack.js' {
  declare module.exports: $Exports<'@blueprintjs/core/lib/esnext/components/panel-stack/panelStack'>;
}
declare module '@blueprintjs/core/lib/esnext/components/panel-stack/panelView.js' {
  declare module.exports: $Exports<'@blueprintjs/core/lib/esnext/components/panel-stack/panelView'>;
}
declare module '@blueprintjs/core/lib/esnext/components/popover/popover.js' {
  declare module.exports: $Exports<'@blueprintjs/core/lib/esnext/components/popover/popover'>;
}
declare module '@blueprintjs/core/lib/esnext/components/popover/popoverArrow.js' {
  declare module.exports: $Exports<'@blueprintjs/core/lib/esnext/components/popover/popoverArrow'>;
}
declare module '@blueprintjs/core/lib/esnext/components/popover/popoverMigrationUtils.js' {
  declare module.exports: $Exports<'@blueprintjs/core/lib/esnext/components/popover/popoverMigrationUtils'>;
}
declare module '@blueprintjs/core/lib/esnext/components/popover/popoverSharedProps.js' {
  declare module.exports: $Exports<'@blueprintjs/core/lib/esnext/components/popover/popoverSharedProps'>;
}
declare module '@blueprintjs/core/lib/esnext/components/popover/popperUtils.js' {
  declare module.exports: $Exports<'@blueprintjs/core/lib/esnext/components/popover/popperUtils'>;
}
declare module '@blueprintjs/core/lib/esnext/components/portal/portal.js' {
  declare module.exports: $Exports<'@blueprintjs/core/lib/esnext/components/portal/portal'>;
}
declare module '@blueprintjs/core/lib/esnext/components/progress-bar/progressBar.js' {
  declare module.exports: $Exports<'@blueprintjs/core/lib/esnext/components/progress-bar/progressBar'>;
}
declare module '@blueprintjs/core/lib/esnext/components/resize-sensor/resizeSensor.js' {
  declare module.exports: $Exports<'@blueprintjs/core/lib/esnext/components/resize-sensor/resizeSensor'>;
}
declare module '@blueprintjs/core/lib/esnext/components/slider/handle.js' {
  declare module.exports: $Exports<'@blueprintjs/core/lib/esnext/components/slider/handle'>;
}
declare module '@blueprintjs/core/lib/esnext/components/slider/handleProps.js' {
  declare module.exports: $Exports<'@blueprintjs/core/lib/esnext/components/slider/handleProps'>;
}
declare module '@blueprintjs/core/lib/esnext/components/slider/multiSlider.js' {
  declare module.exports: $Exports<'@blueprintjs/core/lib/esnext/components/slider/multiSlider'>;
}
declare module '@blueprintjs/core/lib/esnext/components/slider/rangeSlider.js' {
  declare module.exports: $Exports<'@blueprintjs/core/lib/esnext/components/slider/rangeSlider'>;
}
declare module '@blueprintjs/core/lib/esnext/components/slider/slider.js' {
  declare module.exports: $Exports<'@blueprintjs/core/lib/esnext/components/slider/slider'>;
}
declare module '@blueprintjs/core/lib/esnext/components/slider/sliderUtils.js' {
  declare module.exports: $Exports<'@blueprintjs/core/lib/esnext/components/slider/sliderUtils'>;
}
declare module '@blueprintjs/core/lib/esnext/components/spinner/spinner.js' {
  declare module.exports: $Exports<'@blueprintjs/core/lib/esnext/components/spinner/spinner'>;
}
declare module '@blueprintjs/core/lib/esnext/components/tabs/tab.js' {
  declare module.exports: $Exports<'@blueprintjs/core/lib/esnext/components/tabs/tab'>;
}
declare module '@blueprintjs/core/lib/esnext/components/tabs/tabs.js' {
  declare module.exports: $Exports<'@blueprintjs/core/lib/esnext/components/tabs/tabs'>;
}
declare module '@blueprintjs/core/lib/esnext/components/tabs/tabTitle.js' {
  declare module.exports: $Exports<'@blueprintjs/core/lib/esnext/components/tabs/tabTitle'>;
}
declare module '@blueprintjs/core/lib/esnext/components/tag-input/tagInput.js' {
  declare module.exports: $Exports<'@blueprintjs/core/lib/esnext/components/tag-input/tagInput'>;
}
declare module '@blueprintjs/core/lib/esnext/components/tag/tag.js' {
  declare module.exports: $Exports<'@blueprintjs/core/lib/esnext/components/tag/tag'>;
}
declare module '@blueprintjs/core/lib/esnext/components/text/text.js' {
  declare module.exports: $Exports<'@blueprintjs/core/lib/esnext/components/text/text'>;
}
declare module '@blueprintjs/core/lib/esnext/components/toast/toast.js' {
  declare module.exports: $Exports<'@blueprintjs/core/lib/esnext/components/toast/toast'>;
}
declare module '@blueprintjs/core/lib/esnext/components/toast/toaster.js' {
  declare module.exports: $Exports<'@blueprintjs/core/lib/esnext/components/toast/toaster'>;
}
declare module '@blueprintjs/core/lib/esnext/components/tooltip/tooltip.js' {
  declare module.exports: $Exports<'@blueprintjs/core/lib/esnext/components/tooltip/tooltip'>;
}
declare module '@blueprintjs/core/lib/esnext/components/tree/tree.js' {
  declare module.exports: $Exports<'@blueprintjs/core/lib/esnext/components/tree/tree'>;
}
declare module '@blueprintjs/core/lib/esnext/components/tree/treeNode.js' {
  declare module.exports: $Exports<'@blueprintjs/core/lib/esnext/components/tree/treeNode'>;
}
declare module '@blueprintjs/core/lib/esnext/index' {
  declare module.exports: $Exports<'@blueprintjs/core/lib/esnext'>;
}
declare module '@blueprintjs/core/lib/esnext/index.js' {
  declare module.exports: $Exports<'@blueprintjs/core/lib/esnext'>;
}
declare module '@blueprintjs/core/scripts/sass-custom-functions.js' {
  declare module.exports: $Exports<'@blueprintjs/core/scripts/sass-custom-functions'>;
}
