// flow-typed signature: 4dbbc4dc371d31102b91e00811df779d
// flow-typed version: <<STUB>>/@blueprintjs/select_v^3.11.2/flow_v0.118.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@blueprintjs/select'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@blueprintjs/select' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@blueprintjs/select/dist/select.bundle' {
  declare module.exports: any;
}

declare module '@blueprintjs/select/lib/cjs/common/classes' {
  declare module.exports: any;
}

declare module '@blueprintjs/select/lib/cjs/common' {
  declare module.exports: any;
}

declare module '@blueprintjs/select/lib/cjs/common/itemListRenderer' {
  declare module.exports: any;
}

declare module '@blueprintjs/select/lib/cjs/common/itemRenderer' {
  declare module.exports: any;
}

declare module '@blueprintjs/select/lib/cjs/common/listItemsProps' {
  declare module.exports: any;
}

declare module '@blueprintjs/select/lib/cjs/common/listItemsUtils' {
  declare module.exports: any;
}

declare module '@blueprintjs/select/lib/cjs/common/predicate' {
  declare module.exports: any;
}

declare module '@blueprintjs/select/lib/cjs/components' {
  declare module.exports: any;
}

declare module '@blueprintjs/select/lib/cjs/components/omnibar/omnibar' {
  declare module.exports: any;
}

declare module '@blueprintjs/select/lib/cjs/components/query-list/queryList' {
  declare module.exports: any;
}

declare module '@blueprintjs/select/lib/cjs/components/select/multiSelect' {
  declare module.exports: any;
}

declare module '@blueprintjs/select/lib/cjs/components/select/select' {
  declare module.exports: any;
}

declare module '@blueprintjs/select/lib/cjs/components/select/suggest' {
  declare module.exports: any;
}

declare module '@blueprintjs/select/lib/cjs' {
  declare module.exports: any;
}

declare module '@blueprintjs/select/lib/esm/common/classes' {
  declare module.exports: any;
}

declare module '@blueprintjs/select/lib/esm/common' {
  declare module.exports: any;
}

declare module '@blueprintjs/select/lib/esm/common/itemListRenderer' {
  declare module.exports: any;
}

declare module '@blueprintjs/select/lib/esm/common/itemRenderer' {
  declare module.exports: any;
}

declare module '@blueprintjs/select/lib/esm/common/listItemsProps' {
  declare module.exports: any;
}

declare module '@blueprintjs/select/lib/esm/common/listItemsUtils' {
  declare module.exports: any;
}

declare module '@blueprintjs/select/lib/esm/common/predicate' {
  declare module.exports: any;
}

declare module '@blueprintjs/select/lib/esm/components' {
  declare module.exports: any;
}

declare module '@blueprintjs/select/lib/esm/components/omnibar/omnibar' {
  declare module.exports: any;
}

declare module '@blueprintjs/select/lib/esm/components/query-list/queryList' {
  declare module.exports: any;
}

declare module '@blueprintjs/select/lib/esm/components/select/multiSelect' {
  declare module.exports: any;
}

declare module '@blueprintjs/select/lib/esm/components/select/select' {
  declare module.exports: any;
}

declare module '@blueprintjs/select/lib/esm/components/select/suggest' {
  declare module.exports: any;
}

declare module '@blueprintjs/select/lib/esm' {
  declare module.exports: any;
}

declare module '@blueprintjs/select/lib/esnext/common/classes' {
  declare module.exports: any;
}

declare module '@blueprintjs/select/lib/esnext/common' {
  declare module.exports: any;
}

declare module '@blueprintjs/select/lib/esnext/common/itemListRenderer' {
  declare module.exports: any;
}

declare module '@blueprintjs/select/lib/esnext/common/itemRenderer' {
  declare module.exports: any;
}

declare module '@blueprintjs/select/lib/esnext/common/listItemsProps' {
  declare module.exports: any;
}

declare module '@blueprintjs/select/lib/esnext/common/listItemsUtils' {
  declare module.exports: any;
}

declare module '@blueprintjs/select/lib/esnext/common/predicate' {
  declare module.exports: any;
}

declare module '@blueprintjs/select/lib/esnext/components' {
  declare module.exports: any;
}

declare module '@blueprintjs/select/lib/esnext/components/omnibar/omnibar' {
  declare module.exports: any;
}

declare module '@blueprintjs/select/lib/esnext/components/query-list/queryList' {
  declare module.exports: any;
}

declare module '@blueprintjs/select/lib/esnext/components/select/multiSelect' {
  declare module.exports: any;
}

declare module '@blueprintjs/select/lib/esnext/components/select/select' {
  declare module.exports: any;
}

declare module '@blueprintjs/select/lib/esnext/components/select/suggest' {
  declare module.exports: any;
}

declare module '@blueprintjs/select/lib/esnext' {
  declare module.exports: any;
}

// Filename aliases
declare module '@blueprintjs/select/dist/select.bundle.js' {
  declare module.exports: $Exports<'@blueprintjs/select/dist/select.bundle'>;
}
declare module '@blueprintjs/select/lib/cjs/common/classes.js' {
  declare module.exports: $Exports<'@blueprintjs/select/lib/cjs/common/classes'>;
}
declare module '@blueprintjs/select/lib/cjs/common/index' {
  declare module.exports: $Exports<'@blueprintjs/select/lib/cjs/common'>;
}
declare module '@blueprintjs/select/lib/cjs/common/index.js' {
  declare module.exports: $Exports<'@blueprintjs/select/lib/cjs/common'>;
}
declare module '@blueprintjs/select/lib/cjs/common/itemListRenderer.js' {
  declare module.exports: $Exports<'@blueprintjs/select/lib/cjs/common/itemListRenderer'>;
}
declare module '@blueprintjs/select/lib/cjs/common/itemRenderer.js' {
  declare module.exports: $Exports<'@blueprintjs/select/lib/cjs/common/itemRenderer'>;
}
declare module '@blueprintjs/select/lib/cjs/common/listItemsProps.js' {
  declare module.exports: $Exports<'@blueprintjs/select/lib/cjs/common/listItemsProps'>;
}
declare module '@blueprintjs/select/lib/cjs/common/listItemsUtils.js' {
  declare module.exports: $Exports<'@blueprintjs/select/lib/cjs/common/listItemsUtils'>;
}
declare module '@blueprintjs/select/lib/cjs/common/predicate.js' {
  declare module.exports: $Exports<'@blueprintjs/select/lib/cjs/common/predicate'>;
}
declare module '@blueprintjs/select/lib/cjs/components/index' {
  declare module.exports: $Exports<'@blueprintjs/select/lib/cjs/components'>;
}
declare module '@blueprintjs/select/lib/cjs/components/index.js' {
  declare module.exports: $Exports<'@blueprintjs/select/lib/cjs/components'>;
}
declare module '@blueprintjs/select/lib/cjs/components/omnibar/omnibar.js' {
  declare module.exports: $Exports<'@blueprintjs/select/lib/cjs/components/omnibar/omnibar'>;
}
declare module '@blueprintjs/select/lib/cjs/components/query-list/queryList.js' {
  declare module.exports: $Exports<'@blueprintjs/select/lib/cjs/components/query-list/queryList'>;
}
declare module '@blueprintjs/select/lib/cjs/components/select/multiSelect.js' {
  declare module.exports: $Exports<'@blueprintjs/select/lib/cjs/components/select/multiSelect'>;
}
declare module '@blueprintjs/select/lib/cjs/components/select/select.js' {
  declare module.exports: $Exports<'@blueprintjs/select/lib/cjs/components/select/select'>;
}
declare module '@blueprintjs/select/lib/cjs/components/select/suggest.js' {
  declare module.exports: $Exports<'@blueprintjs/select/lib/cjs/components/select/suggest'>;
}
declare module '@blueprintjs/select/lib/cjs/index' {
  declare module.exports: $Exports<'@blueprintjs/select/lib/cjs'>;
}
declare module '@blueprintjs/select/lib/cjs/index.js' {
  declare module.exports: $Exports<'@blueprintjs/select/lib/cjs'>;
}
declare module '@blueprintjs/select/lib/esm/common/classes.js' {
  declare module.exports: $Exports<'@blueprintjs/select/lib/esm/common/classes'>;
}
declare module '@blueprintjs/select/lib/esm/common/index' {
  declare module.exports: $Exports<'@blueprintjs/select/lib/esm/common'>;
}
declare module '@blueprintjs/select/lib/esm/common/index.js' {
  declare module.exports: $Exports<'@blueprintjs/select/lib/esm/common'>;
}
declare module '@blueprintjs/select/lib/esm/common/itemListRenderer.js' {
  declare module.exports: $Exports<'@blueprintjs/select/lib/esm/common/itemListRenderer'>;
}
declare module '@blueprintjs/select/lib/esm/common/itemRenderer.js' {
  declare module.exports: $Exports<'@blueprintjs/select/lib/esm/common/itemRenderer'>;
}
declare module '@blueprintjs/select/lib/esm/common/listItemsProps.js' {
  declare module.exports: $Exports<'@blueprintjs/select/lib/esm/common/listItemsProps'>;
}
declare module '@blueprintjs/select/lib/esm/common/listItemsUtils.js' {
  declare module.exports: $Exports<'@blueprintjs/select/lib/esm/common/listItemsUtils'>;
}
declare module '@blueprintjs/select/lib/esm/common/predicate.js' {
  declare module.exports: $Exports<'@blueprintjs/select/lib/esm/common/predicate'>;
}
declare module '@blueprintjs/select/lib/esm/components/index' {
  declare module.exports: $Exports<'@blueprintjs/select/lib/esm/components'>;
}
declare module '@blueprintjs/select/lib/esm/components/index.js' {
  declare module.exports: $Exports<'@blueprintjs/select/lib/esm/components'>;
}
declare module '@blueprintjs/select/lib/esm/components/omnibar/omnibar.js' {
  declare module.exports: $Exports<'@blueprintjs/select/lib/esm/components/omnibar/omnibar'>;
}
declare module '@blueprintjs/select/lib/esm/components/query-list/queryList.js' {
  declare module.exports: $Exports<'@blueprintjs/select/lib/esm/components/query-list/queryList'>;
}
declare module '@blueprintjs/select/lib/esm/components/select/multiSelect.js' {
  declare module.exports: $Exports<'@blueprintjs/select/lib/esm/components/select/multiSelect'>;
}
declare module '@blueprintjs/select/lib/esm/components/select/select.js' {
  declare module.exports: $Exports<'@blueprintjs/select/lib/esm/components/select/select'>;
}
declare module '@blueprintjs/select/lib/esm/components/select/suggest.js' {
  declare module.exports: $Exports<'@blueprintjs/select/lib/esm/components/select/suggest'>;
}
declare module '@blueprintjs/select/lib/esm/index' {
  declare module.exports: $Exports<'@blueprintjs/select/lib/esm'>;
}
declare module '@blueprintjs/select/lib/esm/index.js' {
  declare module.exports: $Exports<'@blueprintjs/select/lib/esm'>;
}
declare module '@blueprintjs/select/lib/esnext/common/classes.js' {
  declare module.exports: $Exports<'@blueprintjs/select/lib/esnext/common/classes'>;
}
declare module '@blueprintjs/select/lib/esnext/common/index' {
  declare module.exports: $Exports<'@blueprintjs/select/lib/esnext/common'>;
}
declare module '@blueprintjs/select/lib/esnext/common/index.js' {
  declare module.exports: $Exports<'@blueprintjs/select/lib/esnext/common'>;
}
declare module '@blueprintjs/select/lib/esnext/common/itemListRenderer.js' {
  declare module.exports: $Exports<'@blueprintjs/select/lib/esnext/common/itemListRenderer'>;
}
declare module '@blueprintjs/select/lib/esnext/common/itemRenderer.js' {
  declare module.exports: $Exports<'@blueprintjs/select/lib/esnext/common/itemRenderer'>;
}
declare module '@blueprintjs/select/lib/esnext/common/listItemsProps.js' {
  declare module.exports: $Exports<'@blueprintjs/select/lib/esnext/common/listItemsProps'>;
}
declare module '@blueprintjs/select/lib/esnext/common/listItemsUtils.js' {
  declare module.exports: $Exports<'@blueprintjs/select/lib/esnext/common/listItemsUtils'>;
}
declare module '@blueprintjs/select/lib/esnext/common/predicate.js' {
  declare module.exports: $Exports<'@blueprintjs/select/lib/esnext/common/predicate'>;
}
declare module '@blueprintjs/select/lib/esnext/components/index' {
  declare module.exports: $Exports<'@blueprintjs/select/lib/esnext/components'>;
}
declare module '@blueprintjs/select/lib/esnext/components/index.js' {
  declare module.exports: $Exports<'@blueprintjs/select/lib/esnext/components'>;
}
declare module '@blueprintjs/select/lib/esnext/components/omnibar/omnibar.js' {
  declare module.exports: $Exports<'@blueprintjs/select/lib/esnext/components/omnibar/omnibar'>;
}
declare module '@blueprintjs/select/lib/esnext/components/query-list/queryList.js' {
  declare module.exports: $Exports<'@blueprintjs/select/lib/esnext/components/query-list/queryList'>;
}
declare module '@blueprintjs/select/lib/esnext/components/select/multiSelect.js' {
  declare module.exports: $Exports<'@blueprintjs/select/lib/esnext/components/select/multiSelect'>;
}
declare module '@blueprintjs/select/lib/esnext/components/select/select.js' {
  declare module.exports: $Exports<'@blueprintjs/select/lib/esnext/components/select/select'>;
}
declare module '@blueprintjs/select/lib/esnext/components/select/suggest.js' {
  declare module.exports: $Exports<'@blueprintjs/select/lib/esnext/components/select/suggest'>;
}
declare module '@blueprintjs/select/lib/esnext/index' {
  declare module.exports: $Exports<'@blueprintjs/select/lib/esnext'>;
}
declare module '@blueprintjs/select/lib/esnext/index.js' {
  declare module.exports: $Exports<'@blueprintjs/select/lib/esnext'>;
}
