// flow-typed signature: 81d385055108d4efd80f7719c0d48791
// flow-typed version: <<STUB>>/@rematch/immer_v^1.2.0/flow_v0.118.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@rematch/immer'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@rematch/immer' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@rematch/immer/dist/rematch-immer.cjs' {
  declare module.exports: any;
}

declare module '@rematch/immer/dist/rematch-immer.esm' {
  declare module.exports: any;
}

declare module '@rematch/immer/dist/rematch-immer.umd' {
  declare module.exports: any;
}

// Filename aliases
declare module '@rematch/immer/dist/rematch-immer.cjs.js' {
  declare module.exports: $Exports<'@rematch/immer/dist/rematch-immer.cjs'>;
}
declare module '@rematch/immer/dist/rematch-immer.esm.js' {
  declare module.exports: $Exports<'@rematch/immer/dist/rematch-immer.esm'>;
}
declare module '@rematch/immer/dist/rematch-immer.umd.js' {
  declare module.exports: $Exports<'@rematch/immer/dist/rematch-immer.umd'>;
}
